### ISSUE TITLE
Speicherung der durch den Parser gewonnen Daten mit SQL Adapter nicht direkt möglich

### ISSUE THREAD

**Issue by stundenblume** [ioBroker/ioBroker.parser#1]
Eine Speicherung der Daten durch den SQL Adapter sind nicht möglich. Es gibt folgende Fehlermeldung.

> sql.0 Cannot insert INSERT INTO `iobroker`.ts_number (id, ts, val, ack, _from, q) VALUES(195, 1487759025693, 7.2, 1, 12, 0);: Error: ER_DUP_ENTRY: Duplicate entry '195-1487759025693' for key 'PRIMARY'

Es handelt sich um Daten die alle 5min neu eingelesen werden. Wenn die gewonnenen Daten in einer anderen Variablen im javascript adapter abgelegt werden klappt das speichern problemlos.
Nur alle paar Stunden können Daten direkt vom parser in der DB abgelegt werden.

ADMIN und SQL Adapter sind auf dem neuesten Stand.

PS: Dieser Adapter ist einer der wertvollsten!

**Comment by Apollon77** [comment]
Duplicate Entry heisst an sich das der Wert schon da ist. Fehlen die Daten wirklich? Ode rkommt nur der Fehler - dann wäre es eher ein Thema das Parser scheinbar doppelt speichern würde oder so

**Comment by stundenblume** [comment]
> Fehlen die Daten wirklich

Ja, die fehlen wirklich. Anbei mal ein Graph der WindSpeed(WS) direkt (Punkt grün) und über den Umweg einer Variablen (Linie gelb) speichert. Die Einstellungen zum Speichern sind bei beiden Datenpunkten gleich.

![screenshot at 2017-02-24 08 22 51](https://cloud.githubusercontent.com/assets/1537231/23294187/83d73702-fa6a-11e6-8712-32e4256cc08f.png)

**Comment by stundenblume** [comment]
Hier mal alle Fehlermeldungen aus dem aktuellen Log. Es wird trotz unterschiedlicher Uhrzeiten der gleiche primary key verwendet!?

![screenshot at 2017-02-24 08 27 35](https://cloud.githubusercontent.com/assets/1537231/23294369/54165f7e-fa6b-11e6-8315-7004c524b71b.png)

**Comment by Apollon77** [comment]
Wo kommen diese Daten her? Grund ist, dass bei allen der Zeitstempel identisch ist - das ist die zweite lange Zahl nach dem "-" ... in dem Fall "Thu Feb 23 21:13:32 2017 GMT+1:00" Das ist der Grund wie es mir scheint . Scheinbar wird bei einem Update nicht das "ts" des Datenpunkts aktualisiert und damit kommt es zu dem Effekt.

**Comment by stundenblume** [comment]
Die Daten mit dem gleichen timestamp kommen von parser.0. Die die funktionieren kommen von javascript.0
Hier mal ein screenshot:
![screenshot at 2017-02-24 09 36 42](https://cloud.githubusercontent.com/assets/1537231/23296391/0b9d955a-fa75-11e6-8de4-46ffad820973.png)

hier die Einstellungen von parser.0
![screenshot at 2017-02-24 09 39 59](https://cloud.githubusercontent.com/assets/1537231/23296439/59ae1ecc-fa75-11e6-84f8-3e626f727dfe.png)

screenshot javascript.0
![screenshot at 2017-02-24 09 40 15](https://cloud.githubusercontent.com/assets/1537231/23296450/67d8123c-fa75-11e6-8703-6ec4369fbe9f.png)

und so kommen die Daten von WS zu ws:
![screenshot at 2017-02-24 09 43 20](https://cloud.githubusercontent.com/assets/1537231/23296518/b81ed758-fa75-11e6-8e8c-28ba550b40df.png)

**Comment by GermanBluefox** [comment]
Please test new ioBroker.parser from github.

**Comment by stundenblume** [comment]
It seems to work. Thank you very much Bluefox!

![screenshot at 2017-02-24 14 18 53](https://cloud.githubusercontent.com/assets/1537231/23304856/4573c7be-fa9c-11e6-8a06-0c85ae470471.png)
