### ISSUE TITLE
Abfrage funktioniert nicht

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.parser#10]
Guten Tag,

wenn man auf der Seite: https://osthessen-blitzer.de/ mi folgendem regex:
nachricht">(.+)<\/div
eine Abfrage startet funktioniert dies im Zeitablauf nicht.

Ablauf:
Ich habe im parser 10 Abfragen erstellt (Num 1-10).
Diese werden beim 1.Start des parsers korrekt befüllt. 
Die regelmäßige Aktualisierung klappt jedoch nicht. 
Es werden dann Ergebnisse teilweise doppelt dargestellt bzw. gar nicht eingetragen.

mfg

**Comment by Apollon77** [comment]
Bitte Instanz auf loglevel debug stellen und Posten. Und auch Screenshot der konfig bitte

**Comment by bahnuhr** [comment]
Beim Start hat Objekte mit Webseite übereingestimmt.

Nach nun 3 x Aktualisierung passt es nicht.
![objekte aktuell](https://user-images.githubusercontent.com/25694404/43717897-4958dba2-9989-11e8-8035-290a1c6b2f65.JPG)
![webseite aktuell](https://user-images.githubusercontent.com/25694404/43717901-4d64c1ca-9989-11e8-8f83-c5c17c35f1ea.JPG)
sowie log:
`

parser.0 | 2018-08-06 14:51:27.317 | debug | analyseData for parser.0.Blitzer_01,  old=Fulda-<strong>Westring</strong> in Höhe der  <strong>Abfahrt Haimbach</strong> kurz vor der Ampel in  einer 60er-Zone</div>, new=Zwischen <strong>Dickenrück/Rot
-- | -- | -- | --
parser.0 | 2018-08-06 14:51:27.317 | debug | analyseData CHECK for parser.0.Blitzer_01,  old=Fulda-<strong>Westring</strong> in Höhe der  <strong>Abfahrt Haimbach</strong> kurz vor der Ampel in  einer 60er-Zone</div>
parser.0 | 2018-08-06 14:51:27.317 | debug | analyseData for parser.0.Blitzer_02, old=In <strong>Petersberg am  Rauschenberg</strong> beim Kindergarten in Richtung Lehnerz in  einer 30er Zone</div>, new=In <strong>Petersberg am  Rauschenberg</stro
parser.0 | 2018-08-06 14:51:27.317 | debug | analyseData CHECK for parser.0.Blitzer_02, old=In  <strong>Petersberg am Rauschenberg</strong> beim  Kindergarten in Richtung Lehnerz in einer 30er Zone</div>
parser.0 | 2018-08-06 14:51:27.317 | debug | analyseData for parser.0.Blitzer_03, old=Zwischen  <strong>Dickenrück/Rotenburg und Lüdersdorf/Bebra</strong>  in einer 50er Zone</div>, new=Zwischen  <strong>Dickenrück/Rotenburg und Lüdersdorf/Bebra</
parser.0 | 2018-08-06 14:51:27.317 | debug | analyseData CHECK for parser.0.Blitzer_03, old=Zwischen  <strong>Dickenrück/Rotenburg und Lüdersdorf/Bebra</strong>  in einer 50er Zone</div>
parser.0 | 2018-08-06 14:51:27.314 | debug | analyseData for parser.0.Blitzer_04, old=Auf der B27 <strong>bei  Hermansspiegel</strong> (Haunetal)</div>, new=Auf der B27  <strong>bei Hermansspiegel</strong> (Haunetal)</div>
parser.0 | 2018-08-06 14:51:27.314 | debug | analyseData CHECK for parser.0.Blitzer_04, old=Auf der B27  <strong>bei Hermansspiegel</strong> (Haunetal)</div>
parser.0 | 2018-08-06 14:51:27.314 | debug | Cannot find number in answer for parser.0.Blitzer_05
parser.0 | 2018-08-06 14:51:27.314 | debug | analyseData CHECK for parser.0.Blitzer_05, old=In <strong>Hünfeld</strong> hinter der Shell-Tankstelle</div>
parser.0 | 2018-08-06 14:51:27.314 | debug | Cannot find number in answer for parser.0.Blitzer_06
parser.0 | 2018-08-06 14:51:27.314 | debug | analyseData CHECK for parser.0.Blitzer_06, old=<strong  style="font-family: Arial; font-size: 16px;">A7 Kassel -  Würzburg</strong>- zwischen AS Fulda-Mitte und Parkplatz Steinhauk  in beiden Richtungen
parser.0 | 2018-08-06 14:51:27.314 | debug | Cannot find number in answer for parser.0.Blitzer_07
parser.0 | 2018-08-06 14:51:27.314 | debug | analyseData CHECK for parser.0.Blitzer_07, old=Auf der L 3176 zwischen  <strong>Oberrombach und Hünfeld</strong> in der 80er  Zone </div>
parser.0 | 2018-08-06 14:51:27.314 | debug | Cannot find number in answer for parser.0.Blitzer_08
parser.0 | 2018-08-06 14:51:27.314 | debug | analyseData CHECK for parser.0.Blitzer_08, old=In  <strong>Hünfeld</strong> bei der Shell Tankstelle in  Richtung Kreisel</div>
parser.0 | 2018-08-06 14:51:27.314 | debug | Cannot find number in answer for parser.0.Blitzer_09
parser.0 | 2018-08-06 14:51:27.314 | debug | analyseData CHECK for parser.0.Blitzer_09, old=In Fulda,   <strong>Zieherser Weg</strong> in Höhe Esperanto in der 30er  Zone</div>
parser.0 | 2018-08-06 14:51:27.314 | debug | Cannot find number in answer for parser.0.Blitzer_10
parser.0 | 2018-08-06 14:51:27.313 | debug | analyseData CHECK for parser.0.Blitzer_10, old=In  <strong>Fulda</strong> an der  <strong>Goerdelerstraße</strong> am Parkplatz bei den  Schulen </div>
parser.0 | 2018-08-06 14:51:27.313 | debug | Process  ["parser.0.Blitzer_10","parser.0.Blitzer_09","parser.0.Blitzer_08","parser.0.Blitzer_07","parser.0.Blitzer_06","parser.0.Blitzer_05","parser.0.Blitzer_04","parser.0.Blitzer_03","parser.0.Blit

`

**Comment by bahnuhr** [comment]
achja, konfig auch noch:
![konfig](https://user-images.githubusercontent.com/25694404/43718075-d5d38744-9989-11e8-8010-27d804586e1f.JPG)

**Comment by GermanBluefox** [comment]
please test 1.0.2

**Comment by bahnuhr** [comment]
Hallo Bluefox,
probier ich mal aus.
Meld mich dann wieder.

P.S.
Wäre es noch möglich, die Objekte die keinen Wert bekommen, also
"Cannot find number in answer for parser.0.Blitzer_07"
diese dann mit "" zu belegen.

mfg

**Comment by bahnuhr** [comment]
Habe es seit mehreren Stunden laufen.
Scheint nun zu klappen.

Den weiteren Punkt packe ich mal in einen Extra Issue.

mfg

**Comment by bahnuhr** [comment]
Alles zurück.
Es passt wieder nicht.

aktuell log:
`

parser.0 | 2018-08-08 12:28:29.510 | debug | analyseData CHECK for parser.0.Blitzer_01, old=B27  <strong>Ortseingang Ludwigsau-Mecklar</strong> Höhe  Bushaltestelle</div>
-- | -- | -- | --
parser.0 | 2018-08-08 12:28:29.510 | debug | analyseData CHECK for parser.0.Blitzer_02, old=In der  <strong>Goerdelerstraße am Petersberg</strong>, Busplatz  Richtung Rauschenberg in einer 30er Zone</div>
parser.0 | 2018-08-08 12:28:29.510 | debug | analyseData CHECK for parser.0.Blitzer_03, old=B27 Richtung  <strong>Fulda zwischen Hünfeld Nord und Hünfeld Süd</strong>  auf einer Brücke Höhe Klärwerk </div>
parser.0 | 2018-08-08 12:28:29.510 | debug | Cannot find number in answer for parser.0.Blitzer_04
parser.0 | 2018-08-08 12:28:29.510 | debug | analyseData CHECK for parser.0.Blitzer_04, old=Bad Soden Salmünster  Ortsteil <strong>Romstal</strong> aus Richtung Kerbersdorf  in einer Tempo 30-Zone</div>
parser.0 | 2018-08-08 12:28:29.510 | debug | Cannot find number in answer for parser.0.Blitzer_05
parser.0 | 2018-08-08 12:28:29.510 | debug | analyseData CHECK for parser.0.Blitzer_05, old=B 27  <strong>Fulda</strong> Richtung Bronnzell in Höhe Abfahrt  Kaiserwiesen</div>
parser.0 | 2018-08-08 12:28:29.510 | debug | Cannot find number in answer for parser.0.Blitzer_06
parser.0 | 2018-08-08 12:28:29.510 | debug | analyseData CHECK for parser.0.Blitzer_06, old=Auf der B27  <strong>bei Hermansspiegel</strong> (Haunetal)</div>
parser.0 | 2018-08-08 12:28:29.510 | debug | Cannot find number in answer for parser.0.Blitzer_07
parser.0 | 2018-08-08 12:28:29.510 | debug | analyseData CHECK for parser.0.Blitzer_07, old=Auf der L 3176 zwischen  <strong>Oberrombach und Hünfeld</strong> in der 80er  Zone </div>
parser.0 | 2018-08-08 12:28:29.510 | debug | Cannot find number in answer for parser.0.Blitzer_08
parser.0 | 2018-08-08 12:28:29.509 | debug | analyseData CHECK for parser.0.Blitzer_08, old=In  <strong>Hünfeld</strong> bei der Shell Tankstelle in  Richtung Kreisel</div>
parser.0 | 2018-08-08 12:28:29.509 | debug | Cannot find number in answer for parser.0.Blitzer_09
parser.0 | 2018-08-08 12:28:29.509 | debug | analyseData CHECK for parser.0.Blitzer_09, old=In Fulda,   <strong>Zieherser Weg</strong> in Höhe Esperanto in der 30er  Zone</div>
parser.0 | 2018-08-08 12:28:29.509 | debug | Cannot find number in answer for parser.0.Blitzer_10
parser.0 | 2018-08-08 12:28:29.509 | debug | analyseData CHECK for parser.0.Blitzer_10, old=In  <strong>Fulda</strong> an der  <strong>Goerdelerstraße</strong> am Parkplatz bei den  Schulen </div>
parser.0 | 2018-08-08 12:28:29.509 | debug | Process  ["parser.0.Blitzer_10","parser.0.Blitzer_09","parser.0.Blitzer_08","parser.0.Blitzer_07","parser.0.Blitzer_06","parser.0.Blitzer_05","parser.0.Blitzer_04","parser.0.Blitzer_03","parser.0.Blit
parser.0 | 2018-08-08 12:28:29.462 | debug | Request URL: https://osthessen-blitzer.de/
parser.0 | 2018-08-08 12:28:29.462 | debug | Do Link: https://osthessen-blitzer.de/
parser.0 | 2018-08-08 12:28:29.462 | debug | States for current Interval (600000):  ["parser.0.Blitzer_10","parser.0.Blitzer_09","parser.0.Blitzer_08","parser.0.Blitzer_07","parser.0.Blitzer_06","parser.0.Blitzer_05","parser.0.Blitzer_04","parse

`
sowie der Quellcode der Seite:

`<div class="cont" style="display: none;"><div class="zeit">12:28</div><div class="nachricht">kopiert von osthessen-blitzer.de</div></div>
            <div class="clr"></div>


            <div class="cont"><div class="zeit">11:23</div><div class="nachricht"><strong>Ortsausgang Schlüchtern</strong> in Richtung <strong>Steinau</strong> beim NormaMarkt
 </div></div>
<div class="clr"></div>
<div class="cont"><div class="zeit">09:28</div><div class="nachricht">In <strong>Fulda</strong> <strong>stadteinwärts</strong> auf der <strong>Bardostrasse</strong>
 </div></div>
<div class="clr"></div>
<div class="cont"><div class="zeit">08:40</div><div class="nachricht">B27 <strong>Ortseingang Ludwigsau-Mecklar</strong> Höhe Bushaltestelle</div></div>
<div class="clr"></div>
<div class="cont"><div class="zeit">08:20</div><div class="nachricht">In der <strong>Goerdelerstraße am Petersberg</strong>, Busplatz Richtung Rauschenberg in einer 30er Zone</div></div>
<div class="clr"></div>
<div class="cont"><div class="zeit">05:22</div><div class="nachricht">B27 Richtung <strong>Fulda zwischen Hünfeld Nord und Hünfeld Süd</strong> auf einer Brücke Höhe Klärwerk </div></div>
<div class="clr"></div>


        <p style="height: 30px;" /></p>`

Fazit:
Passt nicht.

**Comment by bahnuhr** [comment]
Hallo,
habe einen Unterschied gefunden.

Bei manchen steht das ( </div></div>) am Ende der Nachricht in einer neuen Zeile; bei den anderen steht dies direkt nach der Nachricht in der gleichen Zeile.

Bei denen wo dies in der nächsten Zeile steht; diese werden dann von parser nicht übernommen.

Frage:
Kann dies der Grund sein?
Wenn ja, kann man dies beseitigen?

mfg
Dieter

**Comment by GermanBluefox** [comment]
please test 1.0.3

**Comment by GermanBluefox** [comment]
> Wenn ja, kann man dies beseitigen?

Das ist nicht der Fehler. Das ist standard Verhalten. Man kann aber das ändern, so dass auch dein Fall möglich wird.

**Comment by bahnuhr** [comment]
Hast du das schon in 1.0.3 geändert?
Wenn nein, sagt du mir wie ?

mfg
Dieter

**Comment by bahnuhr** [comment]
Hallo Bluefox,
klappt immer noch nicht.
Jetzt sind auf der Homepape wieder 2 Einträge wo das "div" in der nächsten Zeile steht.
Folglich werden diese nicht erfasst.

`

<div class="cont"><div class="zeit">17:47</div><div class="nachricht">In <strong>Philippsthal-Unterneurode</strong> in der Ortsmitte in der Nähe einer Gaststätte</div></div>
--
  | <div class="clr"></div>
  | <div class="cont"><div class="zeit">15:52</div><div class="nachricht">Auf der <strong>B 27 von Neukirchen Richtung Bad Hersfeld</strong> in der 80er Zone unter einer Brücke</div></div>
  | <div class="clr"></div>
  | <div class="cont"><div class="zeit">14:50</div><div class="nachricht">Auf der<strong> B27 Blitzer in einer 80er Zone von Sontra Richtung Bernburg</strong> in Höhe eines Gasthauses.
  | </div></div>
  | <div class="clr"></div>
  | <div class="cont"><div class="zeit">09:32</div><div class="nachricht">In Fulda auf der <strong>Heidelsteinstr.</strong> Höhe <strong>Harley Davidson Shop.</strong></div></div>
  | <div class="clr"></div>
  | <div class="cont"><div class="zeit">07:47</div><div class="nachricht">Am <strong>Eichzagel in Petersberg</strong> in Richtung Lehnerz in einer 30er Zone.</div></div>
  | <div class="clr"></div>
  | <div class="cont"><div class="zeit">07:37</div><div class="nachricht">Auf der<strong> B84 von Rasdorf Richtung Buttlar</strong> in der 60er Zone am Felsenkeller.</div></div>
  | <div class="clr"></div>
  | <div class="cont"><div class="zeit">07:28</div><div class="nachricht"><strong>Am Rauschenberg in Fulda</strong> in einer 30er Zone.</div></div>
  | <div class="clr"></div>
  | <div class="cont"><div class="zeit">07:28</div><div class="nachricht">Auf der<strong> B27 in Fulda</strong>, stadteinwärts in einer 80er Zone.
  | </div></div>
  | <div class="clr"></div>

`

![bild1](https://user-images.githubusercontent.com/25694404/44357692-f668d700-a4b2-11e8-92ad-9ddc0ae7baa9.jpg)


mfg

**Comment by bahnuhr** [comment]
Und jetzt wieder. Sobald "div" in der nächsten Zeile steht, wird dieser Eintrag nicht erfasst.
![bild1](https://user-images.githubusercontent.com/25694404/44595112-67b4cc80-a7c8-11e8-9923-18a217d50e73.jpg)
![bild2](https://user-images.githubusercontent.com/25694404/44595120-6c798080-a7c8-11e8-9c22-0b9a7dc36f8b.jpg)
mfg

**Comment by bahnuhr** [comment]
Ich schaue jeden Tag, ob sich der Entwickler dem Problem mal annimmt.
Vielleicht liegt der Fehler ja auch bei mir.
Wenn ja, was mache ich falsch ?

Das Problem existiert weiterhin.

Schade, dass hier offensichtlich keine Lösung erfolgt.

**Comment by GermanBluefox** [comment]
Richtig wäre: 
`nachricht">(.+?)</div`

**Comment by bahnuhr** [comment]
Danke ich probiers aus.

Habe nur noch ein \ eingefügt, also
nachricht">(.+?)<\/div

Ich hoffe das war richtig.

**Comment by GermanBluefox** [comment]
?

**Comment by bahnuhr** [comment]
Das ? versteh ich nicht.
Mein Hinweis war deutlich und klar beschrieben.
Dachte ich zumindest.

**Comment by GermanBluefox** [comment]
> Danke ich probiers aus.
> Ich hoffe das war richtig.

Wie muss daraus schließen ob das jetzt funktioniert oder nicht?

пн, 3 сент. 2018 г. в 18:49, bahnuhr <notifications@github.com>:

**Comment by bahnuhr** [comment]
Konnte bisher noch nicht geprüft werden, weil der Fall "div in einer extra Zeile" bisher noch nicht wieder aufgetreten ist.
Ich berichte dann (wenn es wieder auftritt) ob es klappt oder eben nicht.

**Comment by GermanBluefox** [comment]
Muss noch publishen.
