### ISSUE TITLE
Objekt mit "" belegen wenn num nicht gefunden.

### ISSUE THREAD

**Issue by bahnuhr** [ioBroker/ioBroker.parser#11]
Hallo,
wäre es noch möglich, die Objekte die keinen Wert bekommen, also
"Cannot find number in answer for parser.0.Blitzer_07"
diese dann mit "" zu belegen.

mfg

**Comment by GermanBluefox** [comment]
Es sollte schon mit Ersatzwert funktionieren.

**Comment by bahnuhr** [comment]
Hatte ich probiert und nicht geklappt.
Nun nochmal mit 1.0.3 probiert.
Klappt auch nicht.
![bild1](https://user-images.githubusercontent.com/25694404/43883565-d13b64e6-9bb3-11e8-978a-06a78946098b.jpg)
![bild2](https://user-images.githubusercontent.com/25694404/43883575-d44d659e-9bb3-11e8-8078-8915ab315c8a.jpg)

mfg

**Comment by bahnuhr** [comment]
Hallo Bluefox,

dies klappt nicht.

Mach ich da was falsch ?

mfg

**Comment by bahnuhr** [comment]
Ich schaue jeden Tag, ob sich der Entwickler dem Problem mal annimmt.
Vielleicht liegt der Fehler ja auch bei mir.
Wenn ja, was mache ich falsch ?

Das Problem existiert weiterhin.

Schade, dass hier offensichtlich keine Lösung erfolgt.

**Comment by GermanBluefox** [comment]
Fixed. Please test

**Comment by bahnuhr** [comment]
Ich probiers aus.

**Comment by bahnuhr** [comment]
Hallo Bluefox,

es funktioniert nicht.
Oder ich bekomme es nicht hin.

Habe als Ersatz mal ein Leerzeichen eingegeben.
Dieses wird aber nicht eingetragen in den nicht belegten Objekten.

mfg

**Comment by bahnuhr** [comment]
Ok, liest hier eigentlich noch jemand mit.
Entweder ich versteh es nicht oder der Adapter funktioniert in diesem Punkt nicht.

Das mit dem Ersatzwert klappt bei mir nicht.

Vielleicht gibt es ja hier noch eine Lösung.

**Comment by GermanBluefox** [comment]
Eigentlich sollte es mit diesem commit gefixt sein:
https://github.com/ioBroker/ioBroker.parser/commit/ea9c935593aa5b54670bfa3833af454654648b50#diff-7a9076d6d94e62c13d641aa71f19ae8eR77

Ich habe jetzt extra noch die Versionsnummer geändert auf 1.0.6 damit du unterscheiden kannst.


Viel einfacher wäre, dass du einfach den Fehler korrigierst.

**Comment by bahnuhr** [comment]
Hallo Bluefox,
Danke für die Änderung.
Habe 1.0.6 installiert und berichte dann ob sich etwas ändert.
mfg
