### ISSUE TITLE
Error parsing from ESPEasy json

### ISSUE THREAD

**Issue by shaman1010** [ioBroker/ioBroker.parser#13]
string (example) for parsing http://192.168.1.1/json?tasknr=1&view=sensorupdate

respond:
{
"TaskValues": [
{"ValueNumber":1,
"Name":"Volts",
"NrDecimals":0,
"Value":230
},

Work only string or JSON value from 5 string: 
"Value":230 
but not work RegEx ( "Value":(\d+) ) for get number from string.

**Comment by GermanBluefox** [comment]
Please retest with latest npm version

**Comment by GermanBluefox** [comment]
?
