### ISSUE TITLE
aktualisieren der Werte in dem Objekt parser.x

### ISSUE THREAD

**Issue by 7845258** [ioBroker/ioBroker.parser#14]
Die Werte in dem Objekt parser.x werden ja nur aktualisiert, wenn sich der Wert vom vorherigen Wert geändert hat.

Gibt es eine Möglichkeit, dass sich die Werte, in dem Objekt parser.x , jedesmal aktualisieren auch wenn keine Änderung zum vorherigen Wert statt gefunden hat?

Vielen Dank.

**Comment by Apollon77** [comment]
Was ist denn der Mehrwert ?

**Comment by 7845258** [comment]
Hat sich für mich gelöst und ich brauche die Werte nicht mehr jedesmal aktualisiert zu haben, auch wenn sie sich nicht verändert haben.
Trotzdem vielen Dank.

**Comment by padrino-x** [comment]
@Apollon77
Der Mehrwert wäre, dass man weiß, wie aktuell ein Wert. ;)
Außerdem machen das alle Adapter, die ich nutze, auch so, dafür hat man doch "Zeitstempel" und "letzte Änderung", oder? =)

**Comment by Apollon77** [comment]
Am Ende ist das immer so eine Sache und es geht am Ende um die Anzahl an State-Changes pro Zeiteinheit. Aber ich verstehe was Du meinst.

**Comment by padrino-x** [comment]
Hm, es gibt doch die Einstellung "old", also wenn es keinen (neuen) Wert gibt, dann wird der alte Wert nicht (mit leer) überschrieben.
Könnte man entsprechend nicht auch eine Einstellung "force" haben, sodass der Wert auch dann aktualisiert wird, wenn es keine Änderung gab?
So kann der default states sparen, aber der User kann, wenn er es braucht, mehr einstellen. :)
