### ISSUE TITLE
Aussetzer bei Änderungen bzw. Neustart

### ISSUE THREAD

**Issue by andreasploetz** [ioBroker/ioBroker.parser#15]
Hallo,

ich habe das folgende Problem des Adapters in Zusammenspiel mit iobroker. 

 - es scheint als würden Änderungen (default poll time, etc.) nicht bzw. Nur sporadisch übernommen
 - auch werden nach einem Neustart von iobroker bzw. Änderungen im Adapter nur noch anteilig Werte zurück geschrieben
 - alle anderen Objekte in iobroker werden hingegen seit längerem Akkurat in influxdb geschrieben

Version ist die 1.0.5 obwohl laut iobroker nur die 1.0.1 zur Verfügung steht.

Merkwürdig ist dass es ja teilweise geht und auch im regex test immer die aktuellen Werte ausgelesen werden

Gruß Andreas

**Comment by GermanBluefox** [comment]
Gibt es was in der Browser Konsole beim Konfigurations-Speichern ?

**Comment by andreasploetz** [comment]
Da habe ich keine Probleme aber irgendwie scheinen als Einstellungen nicht übernommen zu werden. Aktuell habe ich wieder das Problem - es wurde eine neue Regel hinzugefügt und aktuell werden gar keine Werte mehr aus den Regeln zurück geschrieben.

Anbei der Log, auf einmal lief es wieder nach einem Neustart.
`

parser.0 | 2018-10-12 20:36:11.960 | debug | analyseData for parser.0.eta.puffer-oben, old=44, new=46
-- | -- | -- | --
parser.0 | 2018-10-12 20:36:11.960 | debug | analyseData CHECK for parser.0.eta.puffer-oben, old=44
parser.0 | 2018-10-12 20:36:11.960 | debug | Process ["parser.0.eta.puffer-oben"] for link http://192.168.1.11:8080//user/var/120/10251/0/0/12242
parser.0 | 2018-10-12 20:36:11.960 | debug | analyseData for parser.0.eta.puffer-unten, old=35, new=37
parser.0 | 2018-10-12 20:36:11.960 | debug | analyseData CHECK for parser.0.eta.puffer-unten, old=35
parser.0 | 2018-10-12 20:36:11.959 | debug | Process ["parser.0.eta.puffer-unten"] for link http://192.168.1.11:8080//user/var/120/10251/0/0/12244
parser.0 | 2018-10-12 20:36:11.951 | debug | analyseData for parser.0.eta.puffer-mitte, old=41, new=42
parser.0 | 2018-10-12 20:36:11.951 | debug | analyseData CHECK for parser.0.eta.puffer-mitte, old=41
parser.0 | 2018-10-12 20:36:11.951 | debug | Process ["parser.0.eta.puffer-mitte"] for link http://192.168.1.11:8080//user/var/120/10251/0/0/12522
parser.0 | 2018-10-12 20:36:11.946 | debug | analyseData for parser.0.eta.puffer-ww, old=49, new=54
parser.0 | 2018-10-12 20:36:11.946 | debug | analyseData CHECK for parser.0.eta.puffer-ww, old=49
parser.0 | 2018-10-12 20:36:11.946 | debug | Process ["parser.0.eta.puffer-ww"] for link http://192.168.1.11:8080//user/var/120/10251/0/0/12271
parser.0 | 2018-10-12 20:36:11.946 | debug | analyseData CHECK for parser.0.eta.fußboden-vorlauf, old=24
parser.0 | 2018-10-12 20:36:11.945 | debug | Process ["parser.0.eta.fußboden-vorlauf"] for link http://192.168.1.11:8080//user/var/120/10102/0/0/12241
parser.0 | 2018-10-12 20:36:11.941 | debug | analyseData CHECK for parser.0.eta.kessel-leistung, old=0
parser.0 | 2018-10-12 20:36:11.941 | debug | Process ["parser.0.eta.kessel-leistung"] for link http://192.168.1.11:8080//user/var/120/10251/0/0/12533
parser.0 | 2018-10-12 20:36:11.941 | debug | analyseData for parser.0.eta.kessel-leistung2, old=15.2, new=14
parser.0 | 2018-10-12 20:36:11.938 | debug | analyseData CHECK for parser.0.eta.kessel-leistung2, old=15.2
parser.0 | 2018-10-12 20:36:11.937 | debug | Process ["parser.0.eta.kessel-leistung2"] for link http://192.168.1.11:8080//user/var/40/10021/0/0/12077
parser.0 | 2018-10-12 20:36:11.931 | debug | analyseData for parser.0.eta.kessel-vorlauf, old=30, new=72
parser.0 | 2018-10-12 20:36:11.931 | debug | analyseData CHECK for parser.0.eta.kessel-vorlauf, old=30
parser.0 | 2018-10-12 20:36:11.931 | debug | Process ["parser.0.eta.kessel-vorlauf"] for link http://192.168.1.11:8080//user/var/40/10021/0/0/12241
parser.0 | 2018-10-12 20:36:11.931 | debug | analyseData CHECK for parser.0.eta.heizkörper-vorlauf, old=26
parser.0 | 2018-10-12 20:36:11.931 | debug | Process ["parser.0.eta.heizkörper-vorlauf"] for link http://192.168.1.11:8080//user/var/120/10101/0/0/12241
parser.0 | 2018-10-12 20:36:11.909 | debug | Request URL: http://192.168.1.11:8080//user/var/40/10021/0/0/12077
parser.0 | 2018-10-12 20:36:11.909 | debug | Do Link: http://192.168.1.11:8080//user/var/40/10021/0/0/12077
parser.0 | 2018-10-12 20:36:11.909 | debug | Request URL: http://192.168.1.11:8080//user/var/40/10021/0/0/12241
parser.0 | 2018-10-12 20:36:11.909 | debug | Do Link: http://192.168.1.11:8080//user/var/40/10021/0/0/12241
parser.0 | 2018-10-12 20:36:11.908 | debug | Request URL: http://192.168.1.11:8080//user/var/120/10101/0/0/12241
parser.0 | 2018-10-12 20:36:11.908 | debug | Do Link: http://192.168.1.11:8080//user/var/120/10101/0/0/12241
parser.0 | 2018-10-12 20:36:11.908 | debug | Request URL: http://192.168.1.11:8080//user/var/120/10102/0/0/12241
parser.0 | 2018-10-12 20:36:11.908 | debug | Do Link: http://192.168.1.11:8080//user/var/120/10102/0/0/12241
parser.0 | 2018-10-12 20:36:11.908 | debug | Request URL: http://192.168.1.11:8080//user/var/120/10251/0/0/12533
parser.0 | 2018-10-12 20:36:11.908 | debug | Do Link: http://192.168.1.11:8080//user/var/120/10251/0/0/12533
parser.0 | 2018-10-12 20:36:11.908 | debug | Request URL: http://192.168.1.11:8080//user/var/120/10251/0/0/12271
parser.0 | 2018-10-12 20:36:11.908 | debug | Do Link: http://192.168.1.11:8080//user/var/120/10251/0/0/12271
parser.0 | 2018-10-12 20:36:11.908 | debug | Request URL: http://192.168.1.11:8080//user/var/120/10251/0/0/12522
parser.0 | 2018-10-12 20:36:11.908 | debug | Do Link: http://192.168.1.11:8080//user/var/120/10251/0/0/12522
parser.0 | 2018-10-12 20:36:11.908 | debug | Request URL: http://192.168.1.11:8080//user/var/120/10251/0/0/12244
parser.0 | 2018-10-12 20:36:11.908 | debug | Do Link: http://192.168.1.11:8080//user/var/120/10251/0/0/12244
parser.0 | 2018-10-12 20:36:11.908 | debug | Request URL: http://192.168.1.11:8080//user/var/120/10251/0/0/12242
parser.0 | 2018-10-12 20:36:11.908 | debug | Do Link: http://192.168.1.11:8080//user/var/120/10251/0/0/12242
parser.0 | 2018-10-12 20:36:11.907 | debug | States for current Interval (150000): ["parser.0.eta.puffer-oben","parser.0.eta.puffer-unten","parser.0.eta.puffer-mitte","parser.0.eta.puffer-ww","parser.0.eta.kessel-leistung","parser.0.eta.fußboden
parser.0 | 2018-10-12 20:36:11.798 | debug | States for current Interval (150000): ["parser.0.eta.puffer-oben","parser.0.eta.puffer-unten","parser.0.eta.puffer-mitte","parser.0.eta.puffer-ww","parser.0.eta.kessel-leistung","parser.0.eta.fußbode
parser.0 | 2018-10-12 20:36:11.778 | info | starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.parser, node: v8.12.0
parser.0 | 2018-10-12 20:36:11.673 | debug | statesDB connected
parser.0 | 2018-10-12 20:36:11.661 | debug | objectDB connected
host.iobroker | 2018-10-12 20:36:11.470 | info | instance system.adapter.parser.0 started with pid 3393
host.iobroker | 2018-10-12 20:36:09.470 | info | instance system.adapter.parser.0 terminated with code 0 (OK)
host.iobroker | 2018-10-12 20:36:08.965 | info | stopInstance system.adapter.parser.0 killing pid 3379
host.iobroker | 2018-10-12 20:36:08.965 | info | stopInstance system.adapter.parser.0
host.iobroker | 2018-10-12 20:36:08.964 | info | object change system.adapter.parser.0
parser.0 | 2018-10-12 20:35:43.622 | debug | States for current Interval (150000): []
parser.0 | 2018-10-12 20:35:33.362 | debug | system.adapter.admin.0: logging true
parser.0 | 2018-10-12 20:33:13.611 | debug | States for current Interval (150000): []
influxdb.0 | 2018-10-12 20:33:13.431 | info | enabled logging of eta.puffer-ww, Alias=true
influxdb.0 | 2018-10-12 20:33:04.727 | info | enabled logging of eta.puffer-unten, Alias=true
influxdb.0 | 2018-10-12 20:32:53.929 | info | enabled logging of eta.puffer-oben, Alias=true
influxdb.0 | 2018-10-12 20:32:45.308 | info | enabled logging of eta.puffer-mitte, Alias=true
influxdb.0 | 2018-10-12 20:32:34.782 | info | enabled logging of eta.kessel-vorlauf, Alias=true
influxdb.0 | 2018-10-12 20:32:13.229 | info | enabled logging of eta.kessel-leistung2, Alias=true
influxdb.0 | 2018-10-12 20:32:02.819 | info | enabled logging of eta.kessel-leistung, Alias=true
influxdb.0 | 2018-10-12 20:31:50.319 | info | enabled logging of eta.fußboden-vorlauf, Alias=true
influxdb.0 | 2018-10-12 20:31:45.322 | info | enabled logging of eta.heizkörper-vorlauf, Alias=true
influxdb.0 | 2018-10-12 20:31:29.935 | info | enabled logging of eta.fußboden-vorlauf, Alias=true

`

**Comment by Apollon77** [comment]
Bitte kommende 1.1.0 versuchen und berichten bzw mit neuem Log wider öffnen
