### ISSUE TITLE
HTTPDigestAuth 

### ISSUE THREAD

**Issue by AlexanderSch90** [ioBroker/ioBroker.parser#17]
Ist es möglich eine Seite mit HTTPDigestAuth Login-Daten zu parsen? 

Beim Aufruf der Website wird ein Benutzername und Passwort abgefragt. 
http://user:password@website.de geht hier nicht, wahrscheinlich wegen HTTPDigestAuth 

Danke euch!

**Comment by ChristianHerget** [comment]
Habe das gleiche Problem, ich denke es liegt an https://github.com/request/request/issues/2388
Habe main,js entsprechend gepachtet dann ging es mal für ein paar Minuten, hat dann aber wieder aufgehört.

**Comment by Apollon77** [comment]
Ok,next version is setting "method: GET"
