### ISSUE TITLE
Was ist Num?

### ISSUE THREAD

**Issue by hfuerst** [ioBroker/ioBroker.parser#23]
Ist in readme.md nicht beschrieben...

**Comment by Homoran** [comment]
NUM ist die Fundstelle-1.

falls der RegEx mehrfach auftritt kann man so einen einfacheren RegEx nehmen und über die Position das richtige Ergebnis auswählen.

0=erste Fundstelle
1= zweite Fundstelee
usw.

**Comment by Mic-M** [comment]
Danke für die Erklärung. Habe ich in der Adapter-ReadMe ergänzt, siehe Pull Request: https://github.com/ioBroker/ioBroker.parser/pull/25
