### ISSUE TITLE
[Feature Request] Quelle einmal auslesen und multiple Werte parsen

### ISSUE THREAD

**Issue by Mic-M** [ioBroker/ioBroker.parser#24]
Hi,

wenn man von einer Website (immer selbe URL) mehrere Werte gleichzeit parsen möchte, so legt man pro zu "parsenden" Wert eine Zeile an. Problem: dadurch wird dieselbe URL für jede Zeile immer neu wieder abgefragt. 

**Feature Request:**
Performanter wäre es, wenn der Parser die URL nur jeweils einmalig auslesen würde, im Speicher behalten, und man dann mehrere Werte parsen daraus parsen könnte. Außerdem besteht die (theoretische) Gefahr bei manchen Websites, dass durch den Parser-Adapter zu oft abgefragt wird bei mehreren / einigen Werten, und diese dann womöglich die IP sperren.
In der Adapter-Konfiguration könnte man also mit 2 "Levels" arbeiten:
 1) Auszulesende URL, + Intervall
 2) Darunter dann die einzelnen Regex für die Datenpunkte.

Use Case: siehe z.B. hier: https://forum.iobroker.net/post/306191

**Comment by Apollon77** [comment]
Der Adapter erkennt gleiche URLs und fragt diese an sich nur einmalig ab.

**Comment by Apollon77** [comment]
Ps: genau diese Antwort steht auch im verlinkten forum thread. 

Also was genau wäre der request?

**Comment by Mic-M** [comment]
Sorry @Apollon77 , ich hatte die Antwort im verlinkten Thread nicht gesehen, hatte das Forum-JavaScript nicht geladen und die Frage erschien als letzter Post.

> Wenn bei allen Datenpunkten die gleiche URL hinterlegt ist, wird diese 1mal pro Interval abgerufen und dann laufen alle deine 100 regex darüber

Ich werde über einen Pull-Request diese Info in die adapter-ReadMe übernehmen.

**Comment by Apollon77** [comment]
Danke!

**Comment by Mic-M** [comment]
Hier ergänzt: https://github.com/ioBroker/ioBroker.parser/pull/26
