### ISSUE TITLE
Can not longer edit 

### ISSUE THREAD

**Issue by solarsnoop** [ioBroker/ioBroker.parser#244]
I really irritating because today i want add an entry in the Parser adapter , but i don't see any entry's and can not add any entry. 
But I see an error message:

Cannot import from custom/customComponents.js: ChunkLoadError: Loading chunk vendors-node_modules_mui_private-theming_ThemeProvider_ThemeProvider_js-node_modules_mui_styl-678b53 failed. (error: http://192.168.178.2:8083/adapter/parser/custom/static/js/vendors-node_modules_mui_private-theming_ThemeProvider_ThemeProvider_js-node_modules_mui_styl-678b53.1ba58343.chunk.js)

I dont under this error, so i downgrade and update again the adapter, but no change. I also add the Adapter a second time but same.
The strange is, all Opject are still available, and my scripts are working. The only problem, i can`t add or change an entry. 

Maybe some went wrong with my rasp pi 4 , i am up to date with Raspbian Linux 11. I hope i can get a tip what i can do for fix this issue

![praser_error](https://github.com/ioBroker/ioBroker.parser/assets/40702156/9fc9343d-4e06-47ba-80cf-e0d09dcd058b)

**Comment by TA2k** [comment]
Same here after update to admin 7 and js controller 6
Same in the acme adapter log tab

**Comment by TA2k** [comment]
With GitHub version I receive:

Cannot import from custom/customComponents.js: TypeError: Class extends value undefined is not a constructor or null

**Comment by mcm1957** [comment]
Admin 7 seems to require Adaption.
Should not be related to js-controller 6

**Comment by solarsnoop** [comment]
Yes the downgrade to 6.17.6 helps and i can see the entrys again 
![downgrade](https://github.com/ioBroker/ioBroker.parser/assets/40702156/957c698d-5f53-444a-abc0-bdff1239379f)
JS 6 is in use, so its only the admin 7 integration what is still missing here . Thanks for make it clear!

**Comment by mcm1957** [comment]
Admin 7 had some major and incompatible changes due tonlongvoverdue react cleanup / update. That requires changes at severalbadapters. For details please ask bluefox ifcrequired.

**Comment by solarsnoop** [comment]
I upgrade again to Admin 7.0.11 after i upgrade parser to 2.2.1 but now i dont see the entrys again:
![2 2 1](https://github.com/ioBroker/ioBroker.parser/assets/40702156/a9584f5e-1ba3-4215-91c4-a6cc1950dfc1)

**Comment by solarsnoop** [comment]
and after go pack to admin 6 with 2.2.1 i got now this error
![error](https://github.com/ioBroker/ioBroker.parser/assets/40702156/26663a8c-be7a-4b59-90bf-a9b6d38ac1df)

**Comment by TA2k** [comment]
For me like in GitHub version
`Cannot import from custom/customComponents.js: TypeError: Class extends value undefined is not a constructor or null`

**Comment by Diginix** [comment]
v2.2.1 doesn't solve the issue. Still not possible to see or edit already existing rules.

<img width="514" alt="image" src="https://github.com/ioBroker/ioBroker.parser/assets/39678667/42a2f626-63ec-431b-a761-18f2769b2a64">

parser: 2.2.1
admin: 7.0.11
js-controller: 6.0.6
nodejs: 20.15.0

**Comment by Negalein** [comment]
same Problem

Adapter: 2.2.1
Node.js: v20.15.0
NPM: 10.7.0
Admin: 7.0.13
JS-Controller: 5.0.19

**Comment by fuchs-1978** [comment]
Same Here

![Screenshot_2024-07-14-14-28-35-343_com android chrome](https://github.com/user-attachments/assets/1e5cc773-0b6e-4b75-aa9a-732473c902a9)


Ich habe ein Master Slave, der Parser läuft auf dem Slave 


Plattform: linux
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1200 MHz
Modell: unknown
RAM: 921.9 MB
System-Betriebszeit: 51 T. 03:39:43
Node.js: v20.13.1
time: 1720960220666
timeOffset: -120
NPM: 10.5.2
Adapter-Anzahl: 624
Datenträgergröße: 29.0 GB
Freier Festplattenspeicher: 22.4 GB
Aktive Instanzen: 1
Pfad: /opt/iobroker/
Betriebszeit: 20:12:05


Das Hauptsystem 


fahr!
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 0 MHz
Modell: QEMU Virtual CPU version 2.5+
RAM: 7.7 GB
System-Betriebszeit: 5 T. 02:15:02
Node.js: v20.15.0
time: 1720960217452
timeOffset: -120
NPM: 10.7.0
Adapter-Anzahl: 624
Datenträgergröße: 8.8 GB
Freier Festplattenspeicher: 1.5 GB
Aktive Instanzen: 36
Pfad: /opt/iobroker/
Betriebszeit: 20:16:47

**Comment by fuchs-1978** [comment]
Same Here 

![Screenshot_2024-07-14-14-28-35-343_com android chrome](https://github.com/user-attachments/assets/20eb2391-c5ee-4a2d-b32b-1f617bfeb214)

Parser läuft auf Slave


Plattform: linux
Betriebssystem: linux
Architektur: arm
CPUs: 4
Geschwindigkeit: 1200 MHz
Modell: unknown
RAM: 921.9 MB
System-Betriebszeit: 51 T. 03:39:43
Node.js: v20.13.1
time: 1720960220666
timeOffset: -120
NPM: 10.5.2
Adapter-Anzahl: 624
Datenträgergröße: 29.0 GB
Freier Festplattenspeicher: 22.4 GB
Aktive Instanzen: 1
Pfad: /opt/iobroker/
Betriebszeit: 20:12:05

Master:

fahr!
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 0 MHz
Modell: QEMU Virtual CPU version 2.5+
RAM: 7.7 GB
System-Betriebszeit: 5 T. 02:15:02
Node.js: v20.15.0
time: 1720960217452
timeOffset: -120
NPM: 10.7.0
Adapter-Anzahl: 624
Datenträgergröße: 8.8 GB
Freier Festplattenspeicher: 1.5 GB
Aktive Instanzen: 36
Pfad: /opt/iobroker/
Betriebszeit: 20:16:47

**Comment by GermanBluefox** [comment]
Please test 2.2.2

**Comment by TA2k** [comment]
Github Version is working for me

**Comment by fuchs-1978** [comment]
Working fine

**Comment by solarsnoop** [comment]
yes its fixed now it working fine for me too, Thank you !

**Comment by australien340** [comment]
I have this simular problem:

parser adapter 2.2.4

**Cannot import from custom/customComponents.js: TypeError: D[a] is undefined**

PlatformBetriebssystem:linux
Architektur:x64
CPUs:4
Geschwindigkeit:2594 MHz
Modell:Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz
RAM:5.9 GB
System-Betriebszeit:90 T. 20:27:27
Node.js:v20.18.2
time:1738163692982
timeOffset:-60
NPM:10.8.2
Adapter-Anzahl:559
Datenträgergröße:19.6 GB
Freier Festplattenspeicher:10.5 GB
Aktive Instanzen:37
Pfad:/opt/iobroker/
Betriebszeit:3 T. 02:42:12
aktiv:true
_nodeCurrent:20.18.2
_nodeNewest:20.18.2
_nodeNewestNext:20.18.2
_npmCurrent:10.8.2
_npmNewest:10.8.2
_npmNewestNext:10.8.2

**Comment by mcm1957** [comment]
Did you notice that this issue is closed sonce more than 6 months?
