### ISSUE TITLE
Kein Zugriff auf die Konfig

### ISSUE THREAD

**Issue by man10to** [ioBroker/ioBroker.parser#266]
Nach dem letzten Update wird im GUI kein Eintrag mehr angezeigt sondern es erscheint diese Fehlermeldung:
Die Abfrage selbst laufen

Cannot import from custom/customComponents.js: ChunkLoadError: Loading chunk vendors-node_modules_mui_private-theming_ThemeProvider_ThemeProvider_js-node_modules_mui_styl-678b53 failed. (error: https://192.168.78.222:8081/adapter/parser/custom/static/js/vendors-node_modules_mui_private-theming_ThemeProvider_ThemeProvider_js-node_modules_mui_styl-678b53.1ba58343.chunk.js)

**Comment by mcm1957** [comment]
Bitte bei jedem issue die betroffenen Versionen angeben

Adapter
Admin
Js-controller
Node
O/s

**Comment by man10to** [comment]
hatte ich zu schnell abgeschickt
Adapter  2.1.0
Admin   7.0.22
Js-controller   6.0.9
Node  v18.20.4
O/s  linux / Ubuntu 20.04

alles seit dem letzten Update

**Comment by man10to** [comment]
so sieht es aktuell aus :

![image](https://github.com/user-attachments/assets/19651132-1dec-49b0-9537-5855d1810566)

**Comment by mcm1957** [comment]
Update parser to 2.2.2
see https://github.com/ioBroker/ioBroker.parser#222-2024-07-14
