### ISSUE TITLE
error with admin console 7.0.22 and parser 2.2.1

### ISSUE THREAD

**Issue by kthemall** [ioBroker/ioBroker.parser#267]
if you upgrade iobroker admin console to 7.0.22 parser does not show your configs

**To Reproduce**  
1. install admin console 7.0.22 and parser 2.2.1
2. open parser
3. see that any config you made is gone

**Expected behavior**  
the configs should still be available

**Versions:**  
 - Adapter version: 2.2.1
 - JS-Controller version: 6.0.9
 - Node version: <node-version>20.16.0
 - Operating system: raspberry pi4 latest raspian

if i go back on the admin console to 6.17.14 everything works as expected.

thx tom

**Comment by kthemall** [comment]
just saw that there is the same problem here: [https://github.com/ioBroker/ioBroker.parser/issues/266](url)

**Comment by mcm1957** [comment]
duplicate #266 - please check existing issues before creating new ones.

And please update parser to 2.2.2
see https://github.com/ioBroker/ioBroker.parser#222-2024-07-14

**Comment by kthemall** [comment]
perfekt, läuft wieder, danke

**Comment by kthemall** [comment]
merci
