### ISSUE TITLE
Adapter isn't working since JS 2.0

### ISSUE THREAD

**Issue by UwesSmartHome** [ioBroker/ioBroker.parser#31]
He fails with correct savings, e.g. REGEX is lost after save and reenter the saved string. For the moment the adapter is no longer useful.

Uwe

**Comment by Apollon77** [comment]
Can you pleas eprovide some more details? nothing ewas really changed in controller 2.x+ that should make a problem here. And partser adapter works for me even with controler 3.2. please add logs and screenshots or such to better describe your problem

**Comment by UwesSmartHome** [comment]
Hello Apollon,

![grafik](https://user-images.githubusercontent.com/45943079/88074387-a64f8f00-cb77-11ea-958a-d6fc86704f7e.png)

in the test field are such signs. I copy my text from the website in and it works. But after save and come back are this sings already in.

![Untitled picture](https://user-images.githubusercontent.com/45943079/88075462-1d395780-cb79-11ea-87fa-da0cecfe1d63.png)

**Comment by UwesSmartHome** [comment]
![grafik](https://user-images.githubusercontent.com/45943079/88075642-5ffb2f80-cb79-11ea-8bd0-69d7a618ea65.png)
Here it is working until I save it. The log file says nothing about the adapter.

**Comment by UwesSmartHome** [comment]
I did find a root cause, I hope. It seems the website is encrypted? But I can't see te html text very clear.
![grafik](https://user-images.githubusercontent.com/45943079/88077716-da2cb380-cb7b-11ea-9c47-956bc005c8d6.png)
![Untitled picture](https://user-images.githubusercontent.com/45943079/88077751-e6187580-cb7b-11ea-9080-b8624e186384.png)

**Comment by UwesSmartHome** [comment]
I found this hint:
![Untitled picture](https://user-images.githubusercontent.com/45943079/88081736-1d3d5580-cb81-11ea-981d-e9faf860c237.png)

**Comment by Apollon77** [comment]
What url you entered?

**Comment by Apollon77** [comment]
no answer, closed, else try 1.1.0
