### ISSUE TITLE
How to get First Certificate?

### ISSUE THREAD

**Issue by FlexerJR** [ioBroker/ioBroker.parser#32]
Hi Developer. I tried to do some parsing at printer website in my network. 
If I enter the URL i get this error.

Any idea how to fix?

parser.0 | 2020-08-09 11:43:31.586 | error | (1951) Cannot read link "https://192.168.178.133/PRESENTATION/ADVANCED/COMMON/TOP": Error: unable to verify the first certificate

Best regards

**Comment by Apollon77** [comment]
try GitHub version and give feedback

**Comment by FlexerJR** [comment]
Ok now it is working. Will open other issue. #32 can be closed
