### ISSUE TITLE
Parser stops working after a while

### ISSUE THREAD

**Issue by Roellen** [ioBroker/ioBroker.parser#33]
Hi. 
Iam using the parcel and it works great - but then suddenly it stops working.
I need to STOP and START the parser again.. then it works... for a while. 

Can't find any log entry... 
It just says this when I restart the parcel instance: 

parser.0 | 2020-10-22 18:21:10.515 | info | (14271) Got terminate signal TERMINATE_YOURSELF
-- | -- | -- | --
parser.0 | 2020-10-22 18:18:13.086 | info | (14271) starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.parser, node: v12.18.3, js-controller: 3.1.6
parser.0 | 2020-10-22 18:18:09.259 | info | (12824) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
parser.0 | 2020-10-22 18:18:09.258 | info | (12824) terminating
parser.0 | 2020-10-22 18:18:08.756 | info | (12824) Got terminate signal TERMINATE_YOURSELF

Not sure how I can find the problem?

**Comment by Apollon77** [comment]
Enable Debug Log and see if this brings mrore info.

Instances - Expert Mode - Column loglevel

**Comment by Roellen** [comment]
Hmm, 
i says "Cannot read link":

2020-10-26 12:01:13.652  - [31merror[39m: parser.0 (4910) Cannot read link "http://192.168.1.46/input_emz.xml": Error: Parse Error: Expected HTTP/

Maybe the device can't handle too much requests? (the parser needs to check the status every 5 seconds)
Iam using this to check the status of the alarm system. 
Sadly there is no iobroker adapter that can communicate with the alarm system directly. 
(https://github.com/ioBroker/AdapterRequests/issues/309)

Thanks,
Frank.

**Comment by Apollon77** [comment]
Ok, please set adapter loglevel to debug and let it run and post log then please

**Comment by Roellen** [comment]
Here is the log file:
https://www.dropbox.com/s/5cbk24qu4cvy2ql/Parser.txt?dl=0
(I could not post it here as it was too long, and I did not knew how to filter it to just show the parser debug lines)

**Comment by Apollon77** [comment]
Ok, and on which tzimpoint it stopped updating?

**Comment by Roellen** [comment]
Hard to say when it stopped working.
As it does not say anything when it stops. 😄

I wanted to make a script that sets an output every 5 seconds and then it checks if the parser updated the state or not.

But then... yesterday my proxmox, iobroker and the NUC completely crashed.
I did a restart.

Since then it seems to work fine!

So maybe the parser needs a reboot so that it works? For whatever reason.

**Comment by Roellen** [comment]
Hmm... it worked fine for 3 days or so - after rebooting.
But now it happens again.
After resetting the parser adapter it works fine. But after a while it stops working and needs to be resettet.

I don‘t know what you mean with  „tzimpoint“? Can’t even find anything on google about what it means. 🤔

**Comment by Apollon77** [comment]
timepoint

**Comment by Roellen** [comment]
Zuerst hat der Parser ca. 1-2 Tage gelaufen bevor nichts mehr ging. 

Nun dauert es nur ca. 5 Minuten, dann kommt folgende Meldung: 

parser.0 | 2020-11-22 21:25:00.511 | info | (32270) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
parser.0 | 2020-11-22 21:25:00.511 | info | (32270) terminating

Testweise habe ich eine zweite Instanz angelegt - aber es passiert genau das gleiche... der Adapter stoppt nach  Minuten.

**Comment by Apollon77** [comment]
Dann bitte mal Loglevel auf debug stellen und schauen ob es mehr Log gibt

**Comment by Roellen** [comment]
Irgendwie steht der Parser auf "debug". Aber neben der Information über "terminating" steht "info". 

Ich habe den Parser-Adapter mal als zweite Instanz installiert. Und... dieser Parser läuft sogar noch stabil. Komisch. 


parser.0 | 2020-11-24 13:10:00.678 | debug | (3702) Request URL: http://192.168.1.46/input_emz.xml
-- | -- | -- | --
parser.0 | 2020-11-24 13:10:00.678 | debug | (3702) Do Link: http://192.168.1.46/input_emz.xml
parser.0 | 2020-11-24 13:10:00.678 | debug | (3702)  States for current Interval (9000):  ["parser.0.Studio_Scharf","parser.0.Werkstatt_scharf","parser.0.Regie_scharf","parser.0.Frank_Transponder","parser.0.Moschus_Transponder","parser.0.Mama_Tran
parser.0 | 2020-11-24 13:10:00.514 | info | (3702) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
parser.0 | 2020-11-24 13:10:00.514 | info | (3702) terminating
parser.0 | 2020-11-24 13:10:00.012 | info | (3702) Got terminate signal TERMINATE_YOURSELF
parser.0 | 2020-11-24 13:09:52.261 | debug | (3702) analyseData CHECK for parser.0.Parser_Test, old=true
parser.0 | 2020-11-24 13:09:52.260 | debug | (3702) Text not found for parser.0.Haupteingang_Studio
parser.0 | 2020-11-24 13:09:52.260 | debug | (3702) analyseData CHECK for parser.0.Haupteingang_Studio, old=false
parser.0 | 2020-11-24 13:09:52.259 | debug | (3702) Text not found for parser.0.Tür_Studio
parser.0 | 2020-11-24 13:09:52.259 | debug | (3702) analyseData CHECK for parser.0.Tür_Studio, old=false

**Comment by Roellen** [comment]
Hallo. 

Ich habe jetzt 2 Parser Instanzen. 
Eine schmiert nach ca. 1-2 Minuten ab. 
Die andere nach ca. 1 Tag. 
Eine genauere Info warum das passiert kann ich nicht erkennen. 

Du kannst gerne mit Teamviewer bei mir mal draufschauen. Aber wenn's bei allen anderen einwandfrei läuft - dann kann es ja eigentlich nur an meinem System liegen. Alle anderen Adapter die man sonst so installiert laufen einwandfrei. 


parser.0 | 2020-11-26 14:45:00.513 | info | (10329) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
parser.0 | 2020-11-26 14:45:00.512 | info | (10329) terminating
parser.0 | 2020-11-26 14:45:00.011 | info | (10329) Got terminate signal TERMINATE_YOURSELF
parser.0 | 2020-11-26 14:44:56.032 | debug | (10329) analyseData for parser.0.Parser_Test, old=true,new=false
parser.0 | 2020-11-26 14:44:56.031 | debug | (10329) Text not found for parser.0.Parser_Test
parser.0 | 2020-11-26 14:44:56.031 | debug | (10329) analyseData CHECK for parser.0.Parser_Test, old=true

**Comment by Roellen** [comment]
Hmm... both parser instances have a CRON setup to "every minute". 
Poll intervall is set to 5000ms. 

Is 1 minute standard? (not sure if I ever changed something)

**Comment by Apollon77** [comment]
No, look what I wrote!! it is not in the adapter config. You can see that on the instances view. Else post a screenshot please

**Comment by Roellen** [comment]
Here is a quick video: https://www.youtube.com/watch?v=iZl37A0I2t0

**Comment by Apollon77** [comment]
Ok, there is no schedule set (the * * * * is just default when you open and nothing is there

**Comment by Apollon77** [comment]
then lets do the hasrd check with the instance that kills itself after 1-2mins. 
* Stop it in admin (for next steps lets assume it is instance 1
* open an ssh shell
* change in iobroker dir (cd /opt/iobroker)
* call "iobroker debug iot.1" (if this does not work use "node node_modules/iobroker.iot/main.js 1 --debug")
* wait till it ends itself again
* post output here

**Comment by Roellen** [comment]
Haha. Ok. Maybe i SHOULD set it to reset itselfs every 30 minutes or so? (if this fixes it... good) :-)

At ~ 03:30 the parser instance 0 stops:
https://youtu.be/tPrgaZ06AMg?t=329

Message is: 
offline
connection changed: disconnect
Connection lost
reconnect
Connection changed: connect

(it looks like it tries to reconnect but that does not seem to work, for whatever reason)

**Comment by Apollon77** [comment]
Weisste was ... warum auch immer ich iot.0 geschrieben hab ... gemeint war natürlich parser.0 (oder welcher auch immer der "alle 1-2 minuten" ist

**Comment by Roellen** [comment]
2020-11-27 12:57:50.028  - warn: parser.0 (2058) Got terminate signal. Checking desired PID: 0 vs own PID 2058
2020-11-27 12:57:50.029  - warn: parser.0 (2058) Got terminate signal. Checking desired PID: 3352 vs own PID 2058

**Comment by Roellen** [comment]
https://www.youtube.com/watch?v=JCho7VKcJfo

**Comment by Apollon77** [comment]
Ich hab nicht gesagt du sollst den adapter versuchen im Admin nochmal zu starten wenn er an der Shell läuft. Und ja er bleibt im Admin rot wenn du ihn manuell startest. Das ist so

Bitte nochmal und so lange in der Shell laufen lassen bis er wieder von selbst sich beendet!

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by Apollon77** [comment]
fixed in 1.1.0
