### ISSUE TITLE
HTML codierte Rückgabewerte

### ISSUE THREAD

**Issue by muelmark** [ioBroker/ioBroker.parser#34]
Hallo zusammen,

first of all: der Parser Adapter funktioniert wunderbar - Euch vielen Dank für die Entwicklung!

Ich parse mit diesem Adapter u.a. 3 solare Wetterdaten von 
https://www.proplanta.de/Agrar-Wetter/Schemmerhofen-AgrarWetter.html

Ich verwende folgenden Regex (und ja, der könnte hübscher sein, das ist sicher mehr mir als schlechtem Regexer geschuldet :-):
`<td valign='top' align='left' bgcolor='#ffffff' style="padding:4px;" width='20%'><span class='SCHRIFT_FORMULAR_WERTE_MITTE' alt='Bedeckungsgraddes Himmels: ([^ %']*)`

Mit
Num =16, 20, 24 
erhalte ich derzeit für die jeweils die Uhrzeiten 9, 12, 15 Uhr für eine Prognose, ich würde das dann gerne für die Überschussladung / Gerätesteuerung für Eigenverbrauch in der Photovoltaik nutzen.

Jetzt kommt es ab und an auch mal im schönen Oberschwaben vor, dass der Bedeckungsgrad bei 100 Prozent ist. In diesem Fall liefert mir der Regex konform zu dem, was im HTML steht folgendes allerdings HTML codiertes zurück:
`1&#48;&#48;`
Dieser Wert steht für 100 (, % Bedeckung), die Nullen sind nach https://www.toptal.com/designers/htmlarrows/numbers/zero/ einfach HTML codiert.

Wäre es eine Idee, wenn der Parser einen generellen HTML Dekodierungsschritt für alle gelieferten Werte durchführt?
Ein Browser macht das grundsätzlich auch, gibt es hier eine gute Lösung innerhalb des Parser Adapters?

Viele Dank für eine kurze Antwort,
Markus Müller

**Comment by muelmark** [comment]
Hallo @GermanBluefox,

könntest du dir diesen Issue bitte anschauen? 

Sowas würde es schon machen:
var decodeHtmlEntity = function(str) {
  return str.replace(/&#(\d+);/g, function(match, dec) {
    return String.fromCharCode(dec);
  });
};

Vielen Dank,
muelmark

**Comment by wsn0710** [comment]
Hallo Markus, Du hast wahrscheinlich genau das gelöst, was ich suche. Ich habe diesselbe Webseite Proplanta gefunden und will einen anderen Ort nutzen. Ich habe Fotovoltaik und Wärmepumpe für Heizung. Ich möchte die WP nachts nur zuschalten, wenn die Solarprognose für den nächsten Tag schlecht ist.  Kraftstrommäßig schalte ich die WP bei Sonnenschein vom Wärmepumpenstrom auf Solarstrom. Als auszulesender Parameter kommen in Frage Globalstrahlung oder % Sonneneinstrahlung. Leider habe ich vom Prinzip nichts verstanden. Kannst Du mir den Ansatz erklären? Welche Software benutzt Du? Kann man das Auslesen der Werte von der Webseite mit VB oder Delphi programmieren?
