### ISSUE TITLE
commaNumber ist invalid

### ISSUE THREAD

**Issue by Rich990** [ioBroker/ioBroker.parser#36]
Ich habe das Problem, dass beim erstellen eines Wertes mit dem Typ "Nummer mit Komma", im LOG mienes ioBrokers direkt auftaucht:
Object parser.0.Test is invalid: obj.common.type has an invalid value (commaNumber) but has to be one of number, string, boolean, array, object, mixed, file, json
This object will not be created in future versions. Please report this to the developer.

Was kann ich tun?

**Comment by Apollon77** [comment]
Does this issue still occurs? How s the full log looking? Which adapter is logging that error? Admin or parser?
