### ISSUE TITLE
Many Restarts after updating JS-Controller 3.3

### ISSUE THREAD

**Issue by TheBrain26** [ioBroker/ioBroker.parser#38]
Is the behavior of the adapter wanted or ok? The log file shows this message every second after a js-controller update

parser.0	2021-04-30 12:25:00.544	info	Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
parser.0	2021-04-30 12:25:00.542	info	terminating
parser.0	2021-04-30 12:25:00.028	info	Scheduled restart.
parser.0	2021-04-30 12:24:03.891	info	starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.parser, node: v12.22.1, js-controller: 3.3.1
parser.0	2021-04-30 12:24:00.545	info	Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
parser.0	2021-04-30 12:24:00.543	info	terminating
parser.0	2021-04-30 12:24:00.028	info	Scheduled restart.
parser.0	2021-04-30 12:23:03.943	info	starting. Version 1.0.7 in /opt/iobroker/node_modules/iobroker.parser, node: v12.22.1, js-controller: 3.3.1
parser.0	2021-04-30 12:23:00.541	info	Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
parser.0	2021-04-30 12:23:00.536	info	terminating
parser.0	2021-04-30 12:23:00.027	info	Scheduled restart.

**Comment by Apollon77** [comment]
>  parser.0 2021-04-30 12:25:00.028 info Scheduled restart.

This normally means that you have configured a "restart schedule" and the conttroller is repsecting this setting. Also old controller should have done that the same. Please check your confog in Admin and clear(set the restart schedule correctly
