### ISSUE TITLE
Website don`t loaded before analysed

### ISSUE THREAD

**Issue by Arco86** [ioBroker/ioBroker.parser#41]
I tried to extract the Counter Value from this Page: 
https://www.countee.ch/app/de/counter/view/c5ed88eb142de9

The Browser can show the Value in the Quellcode:
`<span class="counter-val-themeable">25</span>`

But with parser i can`t find it.
The Value is not shown in the Quellcode from the Original Website.
The Values are generated after the Site was loaded using some js-scripts on the Website.

**Comment by Apollon77** [comment]
Ok, and how the "parser" adapter should "parse" the value out of the page when the value is generated by Javascript in a browser? SOrry but then this adapter can not help you
