### ISSUE TITLE
Es lässt sich nur eine Veränderung pro Klick auf "Speichern" Button durchführen

### ISSUE THREAD

**Issue by Qlink84** [ioBroker/ioBroker.parser#44]
Verändert man eine Einstellung im Parser Adapter und klickt auf den "Speichern" Button wird diese wie gewünscht übernommen und gespeichert.
Will man danach noch eine Einstellung ändern, ohne dass man das Parser Adapter Fenster schließt, kann man nicht mehr auf den "Speicher" Button klicken.

Einfach reproduzierbar:
1.  "Regel hinzufügen" Button klicken
2. leere Regel löschen
3. "Speichern" Button klicken
4.  "Regel hinzufügen" Button nochmals klicken
5. leere Regel nochmals löschen
6. "Speichern" Button lässt sich nicht klicken

Workaround: Nach jedem Klick auf den "Speichern" Button muss das Parser Adapter Fenster geschlossen werden.

**Comment by GermanBluefox** [comment]
Please retest with 2.x as GUI was completely rewritten.
