### ISSUE TITLE
Value quality keeps GOOD 0x00 than source is not reachable

### ISSUE THREAD

**Issue by hometm** [ioBroker/ioBroker.parser#47]
If parser is running successful- Value appears with quality GOOD.
After disconnecting the host (on which source file is located), the parser seems to be frozen and quality is not set to BAD 0x82.
![image](https://user-images.githubusercontent.com/10582162/147068381-ca620af7-000c-4eae-a941-7b66da14280c.png)
 
If 'edit' is opend (while URL is not reachable) by pen symbol, a empty error occures
![image](https://user-images.githubusercontent.com/10582162/147068557-2060d751-3845-4d84-989a-47da94778b61.png)

**Comment by Apollon77** [comment]
Please install 1.1.0 and provide debug log of such a case
