### ISSUE TITLE
Werte bleiben nach Änderung URL erhalten

### ISSUE THREAD

**Issue by Azathoth88** [ioBroker/ioBroker.parser#51]
Es kommt vor, dass die URL im Adapter geändert wird. In spezifischen Fällen kann es vorkommen, dass beim Parsen temporär kein Wert ermittelt bzw. geparsed werden kann (z.B. weil die Webseite down ist)

Problem an der Sache: Der zuletzt ermittelte Wert bleibt bestehen.
Wenn allerdings kein Ergebnis geparsed werden kann, so sollte der Wert auf NULL zurückgesetzt werden.

**Comment by Apollon77** [comment]
Bitte ein Debug Log posten für so einen Fall. Danke

**Comment by Apollon77** [comment]
Bzw bitte GitHub version ausprobieren. Es gab einen Fehler mit Konfig Updates wenn das Interval gleich geblieben ist dans dann nicht mehr aktualisiert wurde

**Comment by Apollon77** [comment]
Bitte 1.1.0 testen
