### ISSUE TITLE
Aufruf URL: <title>Error</title>  <b>400 Bad Request: No Host Header</b>

### ISSUE THREAD

**Issue by marianchr** [ioBroker/ioBroker.parser#67]
bei Aufruf URL (lokale Adresse)  in Testtext:   http://192.168.1.34

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"xml:lang="en" lang="en">
<head>
<title>Error</title>
</head>
<body>
<b>400 Bad Request: No Host Header</b>
<br/>
/
<br/>
</body>
</html>

![image](https://user-images.githubusercontent.com/109001570/178122849-8a2a5239-c090-4a49-b378-7108dd09f5c9.png)

**Expected behavior**  
Eigentlich erwarte ich den quelltext der URL angezeigt zu bekommen.

Wenn ich die URL http://192.168.1.34 in beliebigen browser eingebe, gelange ich auf Seite und kann Quelltext anzeigen lassen.

<!DOCTYPE html>
<html lang="en-US">
	<head>
		<title>status</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=0.6, maximum-scale=1.0, user-scalable=0">
		<link rel="stylesheet" type="text/css" href="[style.css](view-source:http://192.168.1.34/style.css)">
		<script src="[xpwLibXv2.js](view-source:http://192.168.1.34/xpwLibXv2.js)"></script>
		<script src="[innovativ.js](view-source:http://192.168.1.34/innovativ.js)"></script>
		<script>
			var opakovat = 1;
			var posledny = 0; //posledny dopyt pre pripad striedania dopytov ohladom horenia a vody
			window.onload = function() {
				updateData("aacc335501363600","500");
				setTimeout(function(){updateData("aacc335501222200","300");}, 800);//cas
				setTimeout(function(){updateData("aacc335501000000","500");}, 1000);
				setTimeout(function(){nastavNadrz();}, 500);
			};

Bei anderen lokalen Seiten wie homematic webui, webserver von DSM werden Quelltexte wie erwartet angezeigt.

Was mache ich falsch?

**Versions:**  
 - Adapter version: <parser.0   V1.1.7>
 - io broker V 5.3.8 in docker auf DSM

**Comment by Apollon77** [comment]
Ich denke der Webserver erwartet das "host" in den Request headersn gesetzt ist ... ich schaue die tage mal rein

**Comment by marianchr** [comment]
Hallo Apollon77,
ich wollte mal fragen, ob Du dir mein Problem schon mal angeschaut hast?
Benötigst Du noch irgendwelche Infos?
Vielen Dank!

**Comment by Apollon77** [comment]
Noch keine Zeit gehabt. Kommt noch dran

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by Apollon77** [comment]
please try 1.2.0

**Comment by marianchr** [comment]
Vielen Dank!
mit 1.2.0 

erhalte ich jetzt den Quelltext der Seite  in dem sind aber die interessanten Dinge als __°C geschrieben und nicht mit Wert gefüllt.

Wenn ich im Browser Element untersuchen klicke, finde ich aber: 

Die gleiche Zeile mit dem Wert      <span class="2textUvod" id="teplotaUdaj">21°</span>


Könnt Ihr mir sagen, was ich falsch mache?


Anbei der Quelltext, den ich über parser erhalte (leider ohne Werte):


Vielen Dank für Eure Hilfe!



<!DOCTYPE html>
<html lang="en-US">
	<head>
		<title>status</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=0.6, maximum-scale=1.0, user-scalable=0">
		<link rel="stylesheet" type="text/css" href="style.css">
		<script src="xpwLibXv2.js"></script>
		<script src="innovativ.js"></script>
		<script>
			var opakovat = 1;
			var posledny = 0; //posledny dopyt pre pripad striedania dopytov ohladom horenia a vody
			window.onload = function() {
				updateData("aacc335501363600","500");
				setTimeout(function(){updateData("aacc335501222200","300");}, 800);//cas
				setTimeout(function(){updateData("aacc335501000000","500");}, 1000);
				setTimeout(function(){nastavNadrz();}, 500);
			};
			
			var alarmCas = 0;
			
			function vyplnUdaje(udaje) {
				switch (udaje) {
					case 0x00: // pre index.html
						document.getElementById("ledTkUdaj").textContent = (dvierka == 1) ? strOpen[jazyk] : strClosed[jazyk];
						document.getElementById("teplotaUdaj").textContent = (teplotaT1 > 0x04b0) ? strError[jazyk] : teplotaT1 + "°";
						document.getElementById("klapkaUdaj").textContent = klapkaS1 + "%";
						var nula = "";
						if (casHoreniaMin < 10) {
							nula = "0";
						} else {
							nula = "";
						}
						document.getElementById("casUdaj").textContent = casHoreniaHod + ":" + nula + casHoreniaMin;
						document.getElementById("ledDgUdaj").textContent = (releDg == 0x01) ? strOn[jazyk] : strOff[jazyk];
						document.getElementById("t2Udaj").textContent = (teplotaT2 > 200) ? "ERR" : teplotaT2 + "°";
						document.getElementById("ledPoUdaj").textContent = (relePo == 0x01) ? strOn[jazyk] : strOff[jazyk];
						document.getElementById("t4Udaj").textContent = (teplotaT4 > 200) ? "ERR" : teplotaT4 + "°";
						document.getElementById("t7Udaj").textContent = (teplotaT7 > 200) ? "ERR" : teplotaT7 + "°";
						if (h2oPcb == 0x00) {
							document.getElementById("teplota").style.display = "inline-block";
							document.getElementById("klapka").style.display = "inline-block";
							document.getElementById("cas").style.display = "inline-block";
							document.getElementById("ledTk").style.display = "inline-block";
							document.getElementById("ledDg").style.display = "inline-block";
						} else {
							document.getElementById("teplota").style.display = "none";
							document.getElementById("klapka").style.display = "none";
							document.getElementById("cas").style.display = "none";
							document.getElementById("ledTk").style.display = "none";
							document.getElementById("ledDg").style.display = "none";
						}
						iOSalarm();
						if (h2oPcb == 0x01)
							document.getElementById("novyGraf2").style.display = "block";
						setTimeout(function(){updateData("aacc335501000000","500");}, 200);
						
						break;
					case 0x22:
						var rok = 0;
						if (datumRok <10)
							rok = "200"+datumRok;
						else
							rok = "20"+datumRok;
						var minuty = 0;
						if (datumMin <10)
							minuty = "0"+datumMin;
						else
							minuty = datumMin;
						document.getElementById("casRegulacie").innerHTML = datumDen +"."+ datumMes +"."+ rok +"  "+ datumHod +":"+ minuty;
						if ((datumZdroj == 0x00) && (alarmCas == 0)) {
							alert('Bitte stellen Sie die aktuelle Uhrzeit ein!');
							alarmCas == 1;
						}
						setTimeout(function(){updateData("aacc335501222200","500");}, 30000);
						break;
					case 0x36:
						break;
					default:
						;
				}
			}
			
			function iOSalarm() {
				// maska
				
				// /maska
				var alarm1 = alarm1B;
				var alarmBezWeb;
				var alarm2 = alarm2B;
				var alarmFlag = 0;
				if (alarm1 >= 0x80) {
					alarm1 -= 0x80;
				}
				alarmBezWeb = alarm1;
				var alarmy = "";
				if (alarm1 >= 0x40) {
					alarm1 -= 0x40;
					//alarmy += strAlarm6[jazyk] + "<br>";	
				}
				if (alarm1 >= 0x20) {
					alarm1 -= 0x20;
					if ((h2oPcb == 1) && (1 == 1)) {
						alarmy += strAlarm5[jazyk] + "<br>";	
						alarmFlag = 1;
					}
				}
				if (alarm1 >= 0x10) {
					alarm1 -= 0x10;
					//alarmy += strAlarm4[jazyk] + "<br>";	
				}
				if (alarm1 >= 0x08) {
					alarm1 -= 0x08;
					if ((h2oPcb == 1) && (1 == 1)) {
						alarmy += strAlarm3[jazyk] + "<br>";	
						alarmFlag = 1;
					}
				}
				if (alarm1 >= 0x04) {
					alarm1 -= 0x04;
					if (1 == 1) {
						alarmy += strAlarm2[jazyk] + "<br>";
						alarmFlag = 1;
					}
				}
				if (alarm1 >= 0x02) {
					alarm1 -= 0x02;
					if (1 == 1) {
						alarmy += strAlarm1[jazyk] + "<br>";	
						alarmFlag = 1;
					}
				}
				if (alarm1 >= 0x01) {
					alarm1 -= 0x01;
					//alarmy += strAlarm0[jazyk];	
				}
				
				if (alarm2 >= 0x02) {
					alarm2 -= 0x02;
					if ((h2oPcb == 1) && (1 == 1)) {
						alarmy += strAlarm52[jazyk] + "<br>";	
						alarmFlag = 1;
					}
				}
				if (alarm2 >= 0x01) {
					alarm2 -= 0x01;
					if (1 == 1) {
						alarmy += "Klappenfehler <br>";	
						alarmFlag = 1;
					}
				}
				if (alarmy == "") {
					document.getElementById("alarm").style.display = "none";
					document.getElementById("alarmy").style.display = "none";
				} else {
					if (window.innerWidth > 520)
						document.getElementById("alarmUdaj").innerHTML = alarmy;
					else
						document.getElementById("alarmUdaj").textContent = strAlarm[jazyk];
					document.getElementById("alarm").style.display = "inline-block";
					//document.getElementById("alarmyUdaj").innerHTML = alarmy;
					//document.getElementById("alarmy").style.display = "inline-block";
				}
			}
			
			var img;
			var g0 = 0;
			
			function nastavNadrz() {
				if (g0 == 1) {
					var obrT1 = document.getElementById("teplotaUdaj").textContent;
					var obrS1 = document.getElementById("klapkaUdaj").textContent;
					var obrCas = document.getElementById("casUdaj").textContent;
					var obrTk = document.getElementById("ledTkUdaj").textContent;
					var obrDg = document.getElementById("ledDgUdaj").textContent;
					var obrT2 = document.getElementById("t2Udaj").textContent;
					var obrPo = document.getElementById("ledPoUdaj").textContent;
					var colorPo = (obrPo == "ON") ? "green" : "red";
					var obrT4 = document.getElementById("t4Udaj").textContent;
					var obrT7 = document.getElementById("t7Udaj").textContent;
					//document.getElementById("novyGraf").style.display = "block";
					img = document.getElementById("myGraf");
					if (window.innerWidth > 780) {
						c.width = 775;
						c.height = 375;
						ctx.drawImage(img,0,0,775,375);
						ctx.font = "48px Helvetica";
						ctx.fillText(obrT1,100,60);
						ctx.fillText(obrS1,100,130);
						ctx.fillText(obrCas,100,200);
						ctx.fillText(obrTk,100,270);
						ctx.fillText(obrDg,100,340);
						ctx.fillText(obrT2,380,60);
						//ctx.fillText(obrPo,360,270);
						ctx.fillText(obrT4,560,100);
						ctx.fillText(obrT7,560,300);
						ctx.beginPath();
						ctx.moveTo(450,294);
						ctx.lineTo(483,276);
						ctx.lineTo(483,312);
						ctx.closePath();
						ctx.stroke();
						ctx.fillStyle = colorPo;
						ctx.fill();
					}
					else {  //if (window.innerWidth > 520) {
						c.width = 515;
						c.height = 250;
						ctx.drawImage(img,0,0,515,250);
						ctx.font = "33px Helvetica";
						ctx.fillText(obrT1,65,46);
						ctx.fillText(obrS1,65,93);
						ctx.fillText(obrCas,65,140);
						ctx.fillText(obrTk,65,186);
						ctx.fillText(obrDg,65,233);
						ctx.fillText(obrT2,253,40);
						//ctx.fillText(obrPo,240,186);
						ctx.fillText(obrT4,370,66);
						ctx.fillText(obrT7,370,213);
						ctx.beginPath();
						ctx.moveTo(300,196);
						ctx.lineTo(322,184);
						ctx.lineTo(322,208);
						ctx.closePath();
						ctx.stroke();
						ctx.fillStyle = colorPo;
						ctx.fill();
						
					} /*else {
						c.width = 255;
						c.height = 124;
						ctx.drawImage(img,0,0,255,124);
						ctx.font = "16px Helvetica";
						ctx.fillText(obrT1,32,23);
						ctx.fillText(obrS1,32,46);
						ctx.fillText(obrCas,32,70);
						ctx.fillText(obrTk,32,93);
						ctx.fillText(obrDg,32,116);
						ctx.fillText(obrT2,126,20);
						ctx.fillText(obrPo,110,90);
						ctx.fillText(obrT4,183,33);
						ctx.fillText(obrT7,183,106);
						
					}*/
				}
				setTimeout(function(){nastavNadrz();}, 1000);
			}
		</script>
	</head>
	<body>
		<noscript>JavaScript is disabled! Enable JavaScript for displaying correct data on website!</noscript>
		<div id="header" class="grad">
			<span style="text-align:left;" id="casRegulacie"></span> 
			<img id="logo" src="src/innovativ.gif" alt="INNOVATIV logo">
			<img id="web" id="wwwPng" src="src/png.png" alt="web" style="display:none;">
			
		</div>
		
		
		
		<div style="display:none">
			<img id="myGraf" src="src/nadrz.gif">
		</div>
		<div id="novyGraf2" style="display:none">
			<canvas id="myCanvas" width="1" height="1">Your browser does not support the HTML5 canvas tag. Use the better/newer browser please.</canvas>
			<script>
				var c = document.getElementById("myCanvas");
				var ctx = c.getContext("2d");
				document.getElementById("myGraf").onload = function() {
					g0 = 1;
				}
			</script>
		</div>
		
		<div id="teplota">
			<img class="ikona" id="teplotaPng" src="src/png.png" alt="teplota">
			<span class="textUvod" id="teplotaUdaj" > ---°C </span>
		</div>
		<div id="klapka">
			<img class="ikona" id="klapkaPng" src="src/png.png" alt="klapka">
			<span class="textUvod" id="klapkaUdaj"> ---% </span>
		</div>
		<div id="cas">
			<img class="ikona" id="casPng" src="src/png.png" alt="cas horenia">
			<span class="textUvod" id="casUdaj"> --- </span>
		</div>
		
		<div id="ledTk">
			<img class="ikona" id="tkPng" src="src/png.png" alt="stav dvierok">
			<span class="textUvod" id="ledTkUdaj"> --- </span>
		</div>
		<div id="ledDg">
			<img class="ikona" id="kvDgPng" src="src/png.png" alt="stav digestora">
			<span class="textUvod" id="ledDgUdaj"> --- </span>
		</div>
		
		<div id="ledPo" style="display:none">
			<img class="ikona" id="poPng" src="src/png.png" alt="stav cerpadla">
			<span class="textUvod" id="ledPoUdaj"> --- </span>
		</div>
		<div id="t2" style="display:none">
			<img class="ikona" id="t2Png" src="src/png.png" alt="T2">
			<span class="textUvod" id="t2Udaj"> --°C </span>
		</div>
		<div id="t4" style="display:none">
			<img class="ikona" id="t4Png" src="src/png.png" alt="T4">
			<span class="textUvod" id="t4Udaj"> --°C </span>
		</div>
		<div id="t7" style="display:none">
			<img class="ikona" id="t4Png" src="src/png.png" alt="T7">
			<span class="textUvod" id="t7Udaj"> --°C </span>
		</div>
		<div id="alarm" style="display:none">
			<img class="ikona" id="alarmPng" src="src/png.png" alt="alarm">
			<span class="textUvod" id="alarmUdaj">  </span>
		</div>
		
		<div id="footer" class="grad">
			<input id="grafBtn" class="tlacidlo" type="button" onclick="location.href='graf.html'">
			<input id="nastavenie" class="tlacidlo" type="button" onclick="location.href='set.html'">
		</div>
		<div style="display:none">
			<div id="alarmy" style="display:none">
				
				<span class="textUvod" id="alarmyUdaj">  </span>
			</div>
		</div>
	</body>
</html>

**Comment by Apollon77** [comment]
Nichts was der "parser" Adapter da machen kann. die Seite scheint die Werte dynamisch per JavaScript einzusetzen
