### ISSUE TITLE
Doppelte Regeln, können nicht gelöscht werden

### ISSUE THREAD

**Issue by Flyor** [ioBroker/ioBroker.parser#69]
Ich benutze den Adapter für insgesamt 22 verschiedene Abfragen. Das lief soweit immer perfekt.

Nun wollte ich eine Regel bearbeiten und stellte fest, dass ich statt 22 Regeln 44 Regeln habe (jede Regel doppelt). Es wurden jedoch nur 22 Objekte angelegt. 

Wenn ich die doppelten Regeln alle einzeln lösche und speichere, sind die 44 nach dem Adapter Neustart wieder da. 

Adapterversion: Latest

**Comment by Apollon77** [comment]
Die Frage ist wie die zustandekamen ... Bitte versuch mal manuell aufzuräumen:
* Admin, Expertenmodus aktivieren
* Objekt Tab
* system.adapter.parser.0 auf den Stift gehen
* dort im JSON sollte im bereich "native" diese 44 einträge sein. Bitte mal dort die unnötigen rauswerfen und speichern (vllt vorher sichern das du im zweifel zurück kannst)

**Comment by Flyor** [comment]
Ich kann leider kein native Objekt finden. 
![image](https://user-images.githubusercontent.com/64526892/180409950-87978a18-da80-49d0-8691-61eda4990837.png)

**Comment by Apollon77** [comment]
system.adapzter.parse.0 ... bei DIESEM objekt auf den Strift gehen ganz rechts (ggf Expertenmodus aktivieren). Dort im Potpiup gibt es ein JSON mit einem textuellen bereich "native":

**Comment by Flyor** [comment]
![image](https://user-images.githubusercontent.com/64526892/180427641-16f63f2a-f2fd-4da9-b54d-0ddaae7667eb.png)

Der Popup hat folgenden Inhalt:

{
  "_id": "system.adapter.parser.0",
  "type": "instance",
  "common": {
    "name": "parser",
    "version": "1.1.8",
    "news": {
      "1.1.4": {
        "en": "Fix crash case reported by Sentry",
        "de": "Absturzfall behoben, der von Sentry gemeldet wurde",
        "ru": "Исправить случай сбоя, о котором сообщил Sentry",
        "pt": "Corrigir caso de falha relatado pelo Sentinela",
        "nl": "Herstel crashgeval gemeld door Sentry",
        "fr": "Correction d'un cas de crash signalé par Sentry",
        "it": "Risolto il caso di crash segnalato da Sentry",
        "es": "Solucionar caso de bloqueo informado por Sentry",
        "pl": "Napraw przypadek awarii zgłoszony przez Sentry",
        "zh-cn": "修复 Sentry 报告的崩溃案例"
      },
      "1.1.3": {
        "en": "if regex did not match set defined replacement value (or null)",
        "de": "wenn Regex nicht übereinstimmte definierter Ersatzwert gesetzt (oder null)",
        "ru": "если регулярное выражение не соответствует заданному значению замены (или null)",
        "pt": "se regex não correspondeu ao valor de substituição definido definido (ou nulo)",
        "nl": "als regex niet overeenkomt met de ingestelde vervangingswaarde (of null)",
        "fr": "si regex ne correspond pas à la valeur de remplacement définie définie (ou nulle)",
        "it": "se regex non corrispondeva imposta il valore di sostituzione definito (o null)",
        "es": "si la expresión regular no coincide con el valor de reemplazo definido establecido (o nulo)",
        "pl": "jeśli wyrażenie regularne nie pasuje do ustawionej zdefiniowanej wartości zastępczej (lub null)",
        "zh-cn": "如果正则表达式不匹配设置定义的替换值（或 null）"
      },
      "1.1.2": {
        "en": "Fix initialization of new parser objects",
        "de": "Korrigieren Sie die Initialisierung neuer Parser-Objekte",
        "ru": "Исправить инициализацию новых объектов парсера",
        "pt": "Corrige a inicialização de novos objetos do analisador",
        "nl": "Initialisatie van nieuwe parser-objecten repareren",
        "fr": "Correction de l'initialisation des nouveaux objets d'analyseur",
        "it": "Correzione dell'inizializzazione di nuovi oggetti parser",
        "es": "Arreglar la inicialización de nuevos objetos del analizador.",
        "pl": "Napraw inicjalizację nowych obiektów parsera",
        "zh-cn": "修复新解析器对象的初始化"
      },
      "1.1.1": {
        "en": "IMPORTANT: js-controller 2.0 is required at least now!\nignore self signed ssl certificates\nmake sure object changes do not block further updates of values\nAdd Sentry to get crash reports",
        "de": "WICHTIG: js-controller 2.0 wird jetzt mindestens benötigt!\nIgnoriere selbstsignierte SSL-Zertifikate\nStellen Sie sicher, dass Objektänderungen weitere Aktualisierungen von Werten nicht blockieren\nFügen Sie Sentry hinzu, um Absturzberichte zu erhalten",
        "ru": "ВАЖНО: js-controller 2.0 требуется как минимум сейчас!\nигнорировать самоподписанные ssl-сертификаты\nубедитесь, что изменения объекта не блокируют дальнейшее обновление значений\nДобавьте Sentry, чтобы получать отчеты о сбоях",
        "pt": "IMPORTANTE: o js-controller 2.0 é necessário pelo menos agora!\nignorar certificados SSL autoassinados\ncertifique-se de que as alterações do objeto não bloqueiem mais atualizações de valores\nAdicione o Sentinela para obter relatórios de falhas",
        "nl": "BELANGRIJK: js-controller 2.0 is nu in ieder geval vereist!\nnegeer zelfondertekende ssl-certificaten\nzorg ervoor dat objectwijzigingen geen verdere updates van waarden blokkeren\nVoeg Sentry toe om crashrapporten te krijgen",
        "fr": "IMPORTANT : js-controller 2.0 est requis au moins maintenant !\nignorer les certificats SSL auto-signés\nassurez-vous que les modifications d'objets ne bloquent pas les mises à jour ultérieures des valeurs\nAjoutez Sentry pour obtenir des rapports de plantage",
        "it": "IMPORTANTE: almeno ora è richiesto js-controller 2.0!\nignora i certificati SSL autofirmati\nassicurarsi che le modifiche agli oggetti non blocchino ulteriori aggiornamenti dei valori\nAggiungi Sentry per ottenere rapporti sugli arresti anomali",
        "es": "IMPORTANTE: ¡Se requiere js-controller 2.0 al menos ahora!\nignorar los certificados SSL autofirmados\nasegúrese de que los cambios de objetos no bloqueen más actualizaciones de valores\nAgregue Sentry para obtener informes de fallas",
        "pl": "WAŻNE: js-controller 2.0 jest wymagany przynajmniej teraz!\nzignoruj samopodpisane certyfikaty ssl\nupewnij się, że zmiany obiektów nie blokują dalszych aktualizacji wartości\nDodaj Sentry, aby otrzymywać raporty o awariach",
        "zh-cn": "重要提示：至少现在需要 js-controller 2.0！\n忽略自签名 ssl 证书\n确保对象更改不会阻止值的进一步更新\n添加 Sentry 以获取崩溃报告"
      },
      "1.0.7": {
        "en": "Comma will be replaced automatically by point for the offset and for the factor",
        "de": "Komma wird automatisch durch Punkt für den Offset und für den Faktor ersetzt",
        "ru": "Comma будет автоматически заменена точкой для смещения и для коэффициента",
        "pt": "Vírgula será substituída automaticamente por ponto para o deslocamento e para o fator",
        "nl": "Komma wordt automatisch vervangen door een punt voor de offset en voor de factor",
        "fr": "La virgule sera automatiquement remplacée par un point pour le décalage et pour le facteur",
        "it": "Virgola verrà sostituita automaticamente dal punto per l'offset e per il fattore",
        "es": "La coma se reemplazará automáticamente por punto para el desplazamiento y para el factor",
        "pl": "Przecinek zostanie automatycznie zastąpiony przez punkt przesunięcia i współczynnik",
        "zh-cn": "逗号将自动替换的点偏及的因素"
      },
      "1.0.6": {
        "en": "Substitute values for strings were fixed",
        "de": "Ersatzwerte für Strings wurden behoben",
        "ru": "Заменяемые значения для строк были исправлены",
        "pt": "Valores substitutos para cadeias de caracteres foram corrigidos",
        "nl": "Vervangende waarden voor tekenreeksen zijn opgelost",
        "fr": "Les valeurs de remplacement pour les chaînes ont été fixées",
        "it": "I valori sostitutivi per le stringhe sono stati corretti",
        "es": "Se corrigieron los valores sustitutos de las cadenas",
        "pl": "Zastępczy wartości dla ciągów zostały naprawione",
        "zh-cn": "替代值串是固定的"
      },
      "1.0.5": {
        "en": "Multi-line search allowed",
        "de": "Mehrzeilige Suche erlaubt",
        "ru": "Разрешен многострочный поиск",
        "pt": "Pesquisa em várias linhas permitida",
        "nl": "Multi-line search toegestaan",
        "fr": "Recherche multiligne autorisée",
        "it": "Ricerca multilinea consentita",
        "es": "Búsqueda multilínea permitida",
        "pl": "Dopuszczalne jest wyszukiwanie wielowierszowe",
        "zh-cn": "多线索允许"
      },
      "1.1.5": {
        "en": "Ignore objects without configuration for parser and log it",
        "de": "Objekte ohne Konfiguration für Parser ignorieren und protokollieren",
        "ru": "Игнорировать объекты без конфигурации для парсера и логировать это",
        "pt": "Ignore objetos sem configuração para analisador e registre-os",
        "nl": "Negeer objecten zonder configuratie voor parser en log het in",
        "fr": "Ignorer les objets sans configuration pour l'analyseur et le consigner",
        "it": "Ignora gli oggetti senza configurazione per il parser e registralo",
        "es": "Ignorar objetos sin configuración para el analizador y registrarlo",
        "pl": "Ignoruj obiekty bez konfiguracji dla parsera i loguj je",
        "zh-cn": "忽略没有解析器配置的对象并记录它"
      }
    },
    "title": "Parser",
    "titleLang": {
      "en": "Parser",
      "de": "Parser",
      "ru": "Синтаксический анализатор",
      "pt": "Analisador",
      "nl": "Parser",
      "fr": "Analyseur",
      "it": "Parser",
      "es": "Analizador",
      "pl": "Analizator składni",
      "zh-cn": "分析器"
    },
    "desc": {
      "en": "This adapter allows to extract values from HTTP URLs or from files",
      "de": "Dieser Adapter ermöglicht das Extrahieren von Werten aus HTTP-Seiten oder aus Dateien",
      "ru": "Этот адаптер позволяет извлекать значения из HTTP страниц или файлов",
      "pt": "Este adaptador permite extrair valores de URLs HTTP ou de arquivos",
      "nl": "Met deze adapter kunnen waarden uit HTTP-URL's of uit bestanden worden geëxtraheerd",
      "fr": "Cet adaptateur permet d'extraire des valeurs à partir d'URL HTTP ou de fichiers",
      "it": "Questo adattatore consente di estrarre valori da URL HTTP o da file",
      "es": "Este adaptador permite extraer valores de URL HTTP o de archivos",
      "pl": "Ten adapter umożliwia wyodrębnianie wartości z adresów URL HTTP lub z plików",
      "zh-cn": "这器允许提取价值从HTTP URLs或从文件"
    },
    "authors": [
      "bluefox <dogafox@gmail.com>"
    ],
    "license": "MIT",
    "platform": "Javascript/Node.js",
    "mode": "daemon",
    "loglevel": "info",
    "messagebox": true,
    "materialize": true,
    "icon": "parser.png",
    "webExtension": "lib/parser.js",
    "readme": "https://github.com/ioBroker/ioBroker.parser/blob/master/README.md",
    "keywords": [
      "url",
      "html",
      "file",
      "parser"
    ],
    "dependencies": [
      {
        "js-controller": ">=2.0.0"
      }
    ],
    "extIcon": "https://raw.githubusercontent.com/ioBroker/ioBroker.parser/master/admin/parser.png",
    "type": "logic",
    "plugins": {
      "sentry": {
        "dsn": "https://24bf60e0e158444599caf102391b2f2f@sentry.iobroker.net/172"
      }
    },
    "connectionType": "none",
    "dataSource": "poll",
    "tier": 3,
    "installedFrom": "iobroker.parser@1.1.8",
    "installedVersion": "1.1.8",
    "enabled": true,
    "host": "ubuntu",
    "logLevel": "info"
  },
  "native": {
    "pollInterval": "720000"
  },
  "from": "system.adapter.admin.0",
  "ts": 1658440327943,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "protectedNative": [],
  "encryptedNative": [],
  "notifications": [],
  "instanceObjects": [],
  "objects": [],
  "user": "system.user.admin"
}

**Comment by Flyor** [comment]
Gibt es hierzu schon ein Ansatz? Wenn der Adapter pausiert ist, ich ihn dann bearbeite, kann ich etwas an den Regeln ändern. Es sind dann aber automatisch alle Regeln doppelt angelegt. Will ich speichern, sagt er geht nicht da doppelte Einträge. Dann lösch ich alle doppelten Einträge, speichere, starte den Adapter, und alle Regeln sind wieder doppelt. Die Objekte bleiben nach wie vor einzeln.

**Comment by GermanBluefox** [comment]
Please retest with 2.x
