### ISSUE TITLE
unable to parse webpage with json

### ISSUE THREAD

**Issue by pehon** [ioBroker/ioBroker.parser#72]
**Describe the bug**  
After a upgrade from 1.1.8 to 1.2.0 I'm no more able to parse a webpage with json content.
With 1.1.8 I was able to use something like
.*value":(\d),.*
But with 1.2 i always get [object Object]
The same happen with type "JSON".

**To Reproduce**  
1. Use https://jsonplaceholder.typicode.com/todos/1
2. try to capture "title"

**Expected behavior**  
use type regex and/or type json to get "delectus aut autem"

**Screenshots & Logfiles**  
![grafik](https://user-images.githubusercontent.com/8524124/190486469-830fd8d0-5b93-42ca-a8dc-554464c8e724.png)

**Versions:**  
 - Adapter version: 1.2.0
 - JS-Controller version: 4.0.23
 - Node version: v14.20.0
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by Apollon77** [comment]
Ok, fix will come soon

**Comment by Apollon77** [comment]
v1.2.1 on it's way ... faster use Github :-)

**Comment by pehon** [comment]
wow, that was quick, it's now fixed, thank you!
