### ISSUE TITLE
Seit Update auf 1.3.1 Fehlermeldungen -> Downgrade hilft nicht

### ISSUE THREAD

**Issue by Flyor** [ioBroker/ioBroker.parser#87]
Seit dem Update auf 1.3.1 bekomme ich Fehlermeldungen vom Adapter. Der Vorschautext und somit die Abfrage funktioniert auf den meisten Seiten nicht mehr. 

Folgendes wird ausgeworfen:

`<html>
<body>

host.ubuntu | 2022-12-09 15:53:34.931 | warn | Do not restart adapter system.adapter.parser.0 because restart loop detected
-- | -- | -- | --
host.ubuntu | 2022-12-09 15:53:34.931 | info | Restart adapter system.adapter.parser.0 because enabled
host.ubuntu | 2022-12-09 15:53:34.931 | error | instance system.adapter.parser.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: at processTicksAndRejections (internal/process/task_queues.js:93:5)
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: at readLink (/opt/iobroker/node_modules/iobroker.parser/main.js:342:13)
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.parser/main.js:75:33
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: at Adapter.sendTo (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:6049:41)
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: at StateRedisClient.pushMessage (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:1089:68)
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: at JSON.stringify (<anonymous>)
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: --- property 'socket' closes the circle
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: \| property '_httpMessage' -> object with constructor 'ClientRequest'
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: --> starting at object with constructor 'TLSSocket'
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: TypeError: Converting circular structure to JSON
host.ubuntu | 2022-12-09 15:53:34.931 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
parser.0 | 2022-12-09 15:53:34.380 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
parser.0 | 2022-12-09 15:53:34.380 | info | terminating
parser.0 | 2022-12-09 15:53:33.873 | error | Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property '_httpMessage' -> object with constructor 'ClientRequest' --- property 'socket' closes the circle
parser.0 | 2022-12-09 15:53:33.873 | error | TypeError: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property '_httpMessage' -> object with constructor 'ClientRequest' --- property 'socket' closes the circle at JSON.stringify (<anonymous>) at StateRedisClient.pushMessage (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:1089:68) at Adapter.sendTo (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:6049:41) at /opt/iobroker/node_modules/iobroker.parser/main.js:75:33 at readLink (/opt/iobroker/node_modules/iobroker.parser/main.js:342:13) at processTicksAndRejections (internal/process/task_queues.js:93:5)
parser.0 | 2022-12-09 15:53:33.805 | error | unhandled promise rejection: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property '_httpMessage' -> object with constructor 'ClientRequest' --- property 'socket' closes the circle
parser.0 | 2022-12-09 15:53:33.805 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>`

Die Vorschau der Seite ist leer:

In meinem Beispiel wäre es folgende abgefragte Seite: https://www.brickmerge.de/76178-1_lego-super-heroes-daily-bugle
![image](https://user-images.githubusercontent.com/64526892/206731051-808449fa-17f6-4cbb-b1bb-ada075b7e4d7.png)

Der Fehler betrifft aber nicht nur diese Seite, sondern auch komplett andere Seiten. 
Es gibt jedoch auch Seiten die funktionieren.

Ich hoffe auf Hilfe und stelle gerne weitere Infos zur Verfügung.

PS: Ein Downgrade HAT NICHTS geändert. Evtl. liegt es an einer Inkompatibilität mit etwas anderem?!

**Comment by Apollon77** [comment]
In this case the issue is that the page return an error when is requested and this error is then transported wrong ... fixed in 1.3.2

**Comment by Flyor** [comment]
Danke, allerdings kommt jetzt eine Fehlermeldung, welche auch nach Befragung von Google für mich nicht schlüssig ist, wo der Fehler liegt: 
![image](https://user-images.githubusercontent.com/64526892/206819848-ea22eefe-6035-4d4e-ae4c-ff8367a76acb.png)

**Comment by Apollon77** [comment]
Das ist jetzt das was die Webseite zurückgibt ... hatte ich auch in deinem Log gesehen. 403 heisst normalerweise das ein Login oder so nötig ist ... in jedem Fall ein "Forbidden".

**Comment by Flyor** [comment]
> Das ist jetzt das was die Webseite zurückgibt ... hatte ich auch in deinem Log gesehen. 403 heisst normalerweise das ein Login oder so nötig ist ... in jedem Fall ein "Forbidden".

Danke - allerdings ist es eine ganz normale Seite, welche ich über Monate immer geloggt habe und sie sich nicht verändert hat. Auch andere Seiten welche ich geloggt hab (alle öffentlich, nichts mit irgendwelchen Accounts oder Logins) gibt das jetzt als Fehler zurück, welcher früher nie kam. Hast du evtl. eine Idee wie ich dem Fehler auf den Grund gehen kann? Ich bin mir fast sicher dass es nicht an der Seite bzw. den Seiten liegt, da diese alle gleichzeitig von heute auf morgen nicht mehr funktioniert haben. @Apollon77

**Comment by Apollon77** [comment]
Ehrlich ... keine Ahnung ... bei mir tat Sie im test.

Was passiert denn wenn du an einer SSH Shell ein "curl -v URL" machst?

**Comment by Flyor** [comment]
> 

Wird komplett ausgelesen, so wie es sein soll.

**Comment by Flyor** [comment]
Ich hab jetzt mal etwas geforscht was dabei raus kommt, der Text den der Adapter ausliest ist tatsächlich ne Fehlermeldung, weil entweder Java Script oder Cookies oder beides nicht aktiviert sind - wurde hier irgendetwas am System iobroker bzw. am Adapter geändert, dass dies nicht mehr vorhanden bzw. nicht mehr aktiviert ist? Vielleicht kommen wir der Sache ja auf die Spur... An der HP selbst kann es jedenfalls nicht liegen, sonst wären ja nicht verschiedene HPs gleichzeitig betroffen. @Apollon77 

![image](https://user-images.githubusercontent.com/64526892/206926788-9a0a2dc9-77e7-48b3-9ff0-59d6bcd00520.png)

**Comment by Apollon77** [comment]
Nee das wäre kein http 403 Fehler sondern nur a zeige im Browser. Das ist's nicht.
